packages/env-build-task-driver/internal/env/provision.sh
- https://github.com/e2b-dev/infra/issues/73
> With some Debian versions used as the base for template the envd is not correctly started which results in SDK trying to reconnect until the timeout, then exiting.
> This problem also affects start cmd.
The problem was caused by too specific path to bash binary that was not used on some Debian versions.
=> Fix broken provisioning for some Debian versions

.github/workflows/fc-versions.yml
When we ran the GHA for uploading fc-versions there was a redundant `builds/` top level directory that contained all the versioned directories. The versioned directories should have been on the top level in the bucket.
This change to GHA should fix it — the only strange thing being that we had the same code for uploading fc-kernels, but there was no incorrect `builds/` directory there.
=> Fix upload path for FC versions

packages/cluster/scripts/start-client.sh
When the client is restarted right now the startup script cannot be executed and the VM needs to be manually replaced for everything to work again.
This fixed the problem in the startup script — this does not fix the restarting, it just improves how the recovery is handled.
=> Make client startup script rerunnable

packages/env-build-task-driver/internal/handle.go, packages/env-build-task-driver/internal/task.go, packages/env-instance-task-driver/internal/handle.go, packages/env-instance-task-driver/internal/task.go, packages/shared/pkg/driver/driver.go, packages/template-delete-task-driver/internal/handle.go, packages/template-delete-task-driver/internal/task.go
Right now we are not using Nomad for monitoring resource usage of tasks, but Nomad still keeps throwing errors every second even though the TaskStats if flagged as NotImplemented.
=> Add placeholder stats channel for tasks

packages/nomad/main.tf, packages/nomad/otel-collector.hcl
Fix scraping of Consul metrics by using the Consul token in the request.
=> Use consul token for scraping metrics

packages/env-instance-task-driver/internal/driver.go, packages/env-instance-task-driver/internal/handle.go, packages/env-instance-task-driver/internal/instance/dns.go, packages/env-instance-task-driver/internal/instance/fc.go, packages/env-instance-task-driver/internal/instance/files.go, packages/env-instance-task-driver/internal/instance/instance.go, packages/env-instance-task-driver/internal/instance/mock_instance.go, packages/env-instance-task-driver/internal/instance/network.go, packages/env-instance-task-driver/internal/task.go, packages/env-instance-task-driver/main.go, packages/shared/pkg/telemetry/tracing.go
There is a race condition during sandbox start that may be affecting the networking and start of sandboxes when multiple are started at the same time. (If this is not causing the persistent 502 error then it is probably some thread network namespace switching.)
=> Fix data races in Nomad driver during sandbox start

packages/api/internal/nomad/client.go, packages/api/internal/nomad/jobs.go
Switch from polling Nomad to using stream. This improves API/Nomad performance when handling multiple sandbox requests.
=> Use Nomad stream for getting job allocations

packages/api/internal/nomad/client.go, packages/api/internal/nomad/jobs.go, packages/env-build-task-driver/internal/handle.go, packages/env-build-task-driver/internal/task.go, packages/env-instance-task-driver/Makefile, packages/env-instance-task-driver/internal/driver.go, packages/env-instance-task-driver/internal/handle.go, packages/env-instance-task-driver/internal/instance/dns.go, packages/env-instance-task-driver/internal/instance/fc.go, packages/env-instance-task-driver/internal/instance/files.go, packages/env-instance-task-driver/internal/instance/instance.go, packages/env-instance-task-driver/internal/instance/mock_instance.go, packages/env-instance-task-driver/internal/instance/network.go, packages/env-instance-task-driver/internal/instance/slot.go, packages/env-instance-task-driver/internal/task.go, packages/env-instance-task-driver/main.go, packages/shared/pkg/driver/driver.go, packages/shared/pkg/driver/handle.go, packages/shared/pkg/telemetry/tracing.go, packages/template-delete-task-driver/internal/handle.go, packages/template-delete-task-driver/internal/task.go
The sudden restarts we are sometimes experiencing may be connected to how we are using Nomad. This PR should improve that.
=> Cleanup Nomad job handling and drivers

packages/env-instance-task-driver/internal/instance/fc.go, packages/env-instance-task-driver/internal/instance/mock_instance.go
This moves MMDS setup from a goroutine — errors in MMDS setup will also cancel the sandbox spawn.
Fixes https://github.com/e2b-dev/infra/issues/123
=> Fix missing MMDS in some sandboxes

packages/envd/internal/process/service.go
The buffer for the scanning process stdout and stderr was preallocated and couldn't be dynamically resized.
This hogged up memory and in some cases caused OOM and `envd` restart resulting in timeout in SDK.
Should fix https://github.com/e2b-dev/E2B/issues/339
=> Fix process output scan buffer initialization and resizing

packages/api/internal/handlers/store.go, packages/orchestrator/internal/server/main.go, packages/shared/pkg/logging/logger.go
Add a basic logger to orchestrator
it logs every call to the `stdout`, except health checks and it has a following format
```
2024-04-16T19:41:43Z	info	finished unary call with code OK	{"grpc.start_time": "2024-04-16T19:41:43Z", "system": "grpc", "span.kind": "server", "grpc.service": "Sandbox", "grpc.method": "Create", "grpc.code": "OK", "grpc.time_ms": 109.469}
```
=> gRPC logging

packages/cluster/scripts/run-nomad.sh, packages/cluster/scripts/start-client.sh, packages/cluster/scripts/start-server.sh, packages/envd/internal/clock/service.go
Ensure that Nomad and Consul have at least 65536 as the limit for file descriptors.
=> Set file descriptors' limits

packages/orchestrator/internal/server/sandboxes.go
We called the sandbox cleanup twice when killing the sandbox. This PR removes that and improves the order in which the cleanup handler are called.
=> Remove unnecessary cleanup method and fix cleanup order

packages/nomad/api.hcl, packages/nomad/client-proxy.hcl, packages/nomad/docker-reverse-proxy.hcl, packages/nomad/logs-collector.hcl, packages/nomad/loki.hcl, packages/nomad/orchestrator.hcl, packages/nomad/otel-collector.hcl, packages/nomad/session-proxy.hcl
We called the sandbox cleanup twice when killing the sandbox. This PR removes that and improves the order in which the cleanup handler are called.
=> Remove unnecessary cleanup method and fix cleanup order #140

packages/orchestrator/Makefile, packages/orchestrator/internal/constants/node.go, packages/orchestrator/internal/sandbox/fc.go, packages/orchestrator/internal/sandbox/files.go, packages/orchestrator/internal/sandbox/mock_instance.go, packages/orchestrator/internal/sandbox/process.go, packages/orchestrator/internal/sandbox/sandbox.go, packages/orchestrator/internal/sandbox/slot.go, packages/orchestrator/internal/sandbox/uffd.go, packages/orchestrator/internal/server/main.go, packages/orchestrator/internal/server/sandboxes.go
This PR fixes UFFD and Firecracker process handling in the orchestrator, including starting, killing, and recovering.
The PR finishes the fix started in https://github.com/e2b-dev/infra/tree/soft-kill which should be fixing the unexpected restarting of the client.
=> Fix UFFD and Firecracker killing in orchestrator

packages/template-manager/internal/build/provision.sh
This PR configures small swaps space (limited by free disk) and OOM handling of envd and start command to prevent the most frequent OOM during sandbox usage. For proper OOM handling the zram/zswap and other OOM handling techniques (envd child process oom adjust) should be explored.
After we merge this we should rebuild the templates:
=> Add swap and adjust OOM handling in sandbox

spec/openapi.yml
This PR adds a parameter during sandbox creation that allows specifying the sandbox timeout and a route that allows modifying the timeout after creation.
This is compatible with the way sandboxes are currently handled but allows us to change how the sandbox lifecycle is managed (without constant refreshes, setting a maximum timeout, or extending timeout) just by modifying SDKs' code.
Tasks
=> Allow specifying sandbox timeout when creating the sandbox and modifying it later

packages/api/internal/handlers/sandbox_create.go, packages/api/internal/handlers/store.go, packages/envd/Makefile, packages/envd/internal/log/exporter/exporter.go, packages/envd/internal/log/exporter/mmds.go, packages/envd/internal/process/manager.go, packages/envd/internal/process/process.go, packages/envd/internal/process/service.go, packages/envd/main.go, packages/fc-envs-disk/Makefile, packages/nomad/api.hcl, packages/nomad/main.tf, packages/shared/pkg/logging/collector.go, packages/shared/pkg/logging/exporter/exporter.go, packages/template-manager/internal/build/provision.sh, packages/template-manager/internal/build/rootfs.go
Right now the start cmd is managed by systemd. This PR changed it so it is managed by envd which allows us better control over it and also allows integration with logging.
Tasks
=> Manage start command in envd

packages/api/internal/cache/instance/sync.go, packages/api/internal/handlers/sandbox_refresh.go, packages/api/internal/handlers/sandbox_timeout.go
- The timeout of the sandbox can be set to shorter period
=> Allow to shorten sandbox duration

packages/envd/internal/services/process/handler/handler.go
We use an external package to start process with PTY. But the package starts process already when creating the process handler. We were trying the process again in `Start()` method
=> Process with PTY - start only once

packages/cluster/scripts/start-client.sh
To improve DX you can now run only 
```bash
sbx-ssh <sandboxID>
```
and you will be directly connected to the sandbox.
=> Add sandbox SSH alias

packages/shared/pkg/db/envs.go
Some fields returned by API were not returned in GetEnvs method, oops 
<details open>
This PR adds the `UpdatedAt` field to the return value of the `GetEnvs` method, ensuring that all relevant fields from the API are included.
<details>
```mermaid
participant DB as Database
participant Env as Environment Object
DB->>Env: Get Environment Item
Note over Env: Add UpdatedAt field
Env->>DB: Store Environment with UpdatedAt
```
</details>
<details>
<summary><b>Files Changed</b></summary>
<table>
<tr><th>File</th><th>Summary</th></tr>
<tr><td><a href=https://github.com/e2b-dev/infra/pull/207/files#diff-72605933de264b01510f45a7ace429435b165b3c018bbd47a1be10abc …
=> Small oversight with template fields

packages/api/internal/handlers/sandbox_logs.go, packages/api/internal/handlers/sandboxes_list.go, packages/shared/pkg/logs/logger.go
In order to return sorted running instances by start time, this PR updates the `APIStore.GetSandboxes` method in a way where the final returned slice is sorted descending by the `StartedAt` field. 
Tested in js-sdk https://github.com/e2b-dev/E2B/pull/489
<details open>
This PR updates the `APIStore.GetSandboxes` method to return running instances sorted in descending order by their `StartedAt` field. It also modifies the log sorting mechanism to use the new `slices` package for sorting.
<details>
```mermaid
participant SandboxHandler
participant Logger
participant LogExporter
Client->>SandboxHandler: Request Sandbox Logs …
```
=> Sort the sandboxes based on the start time

go.work.sum, packages/envd/Makefile, packages/envd/go.mod, packages/envd/go.sum, packages/envd/internal/api/api.gen.go, packages/envd/internal/api/store.go, packages/envd/internal/host/metrics.go, packages/envd/spec/envd.yaml, packages/shared/Makefile
This PR adds a `/metrics` endpoint to the envd API. This is the first step in allowing the orchestrator to poll for metrics in individual sandboxes from within. 
```sh
cd packages/envd 
make generate
make run-envd &
curl localhost:49983/metrics
```
<details open>
This PR introduces a new `/metrics` endpoint to the envd API, allowing the orchestrator to poll for metrics from individual sandboxes. It includes the implementation of metrics retrieval and updates to the API interface and routing.
<details>
```mermaid
participant API Server
participant Host System
Client->>API Server: GET /metrics
API Server->>Host System: GetMetrics() …
```
=> Envd metrics endpoint

packages/shared/pkg/db/envs.go
Right now, snapshots envs are also listed when listing templates. This change filters them out.
<details open>
This PR filters out snapshots from the templates API endpoint by modifying the query to exclude environments that have snapshots.
<details>
```mermaid
participant C as Client
participant DB as Database Query
participant E as Environments
C->>DB: Query Environments
Note over DB: Filter Conditions:<br/>1. Match Team ID<br/>2. Has Uploaded Builds<br/>3. No Snapshots
DB->>E: Apply Filters
E-->>C: Return Filtered Environments
```
</details>
<details>
<summary><b>Files Changed</b></summary>
<table>
<tr><th>File</th><th>Summary</th></tr>
<tr><td><a …
=> Filter out snapshots from templates API endpoint

packages/api/internal/cache/instance/instance.go, packages/orchestrator/internal/server/sandboxes.go
Remove the sandbox from cache prior ending the sandbox itself
<details open>
This PR modifies the sandbox deletion process to ensure the sandbox is removed from the cache before stopping it, preventing potential issues if the sandbox gets stuck.
<details>
```mermaid
participant Server
participant DNS
participant Cache
participant Sandbox
Client->>Server: StopSandbox(sandboxId)
Server->>DNS: Remove(sandboxId)
Server->>Cache: Remove(sandboxId)
Server->>Sandbox: Healthcheck(ctx, true)
Server->>Sandbox: Stop()
Server->>Client: Return Empty Response
```
</details>
<details>
<summary><b>Files Changed</b></summary>
<table> …
=> Prevent problem if closing sandbox gets stuck

packages/envd/README.md, packages/envd/internal/api/init.go, packages/envd/main.go
Set a  `E2B_SANDBOX=true` env var inside the sandbox as soon as it envd inits. 
Users will then be able to get this env var from the code running inside the sandbox (as if they were trying to get any other env var) and tell if the code is running inside the sandbox.
Going to try this test in `js-sdk`, cannot do it on local host. 
```js
sandboxTest.skipIf(isDebug)('default env vars present', async ({ sandbox }) => {
const result = await sandbox.commands.run('echo $E2B_SANDBOX')
assert.equal(result?.stdout[0].trim(), 'true')
})
```
And in `code-interpreter` 
```js
sandboxTest.skipIf(isDebug)('default env vars present', async ({ sandbox }) => {
const result = await sandbox.runCode('import os; os.getenv("E2B_SANDBOX")')
expect(result.results[0].text.trim()).toEqual('true')
})
```
<details …
=> Set default IS_SANDBOX env var upon envd init

packages/cluster/scripts/start-api.sh, packages/cluster/scripts/start-client.sh, packages/cluster/server/main.tf
The DNS records weren't updated on the node, causing issues if the node with e.g. template manager was replaced
<details open>
This PR adds a missing DNS request token to the startup scripts for both API and client, ensuring proper DNS record updates on the node.
<details>
```mermaid
participant Cluster Scripts
participant Consul
participant GCP Instance
Cluster Scripts->>Consul: Add gossip encryption key
Cluster Scripts->>Consul: Add DNS request token
GCP Instance->>GCP Instance: Enable OS Config
GCP Instance->>GCP Instance: Enable Guest Attributes
Note over Cluster Scripts,Consul: Enhanced security configuration
Note over GCP Instance: Additional …
```
=> Add missing DNS request token

packages/api/internal/handlers/template_start_build.go, packages/api/internal/template-manager/create_template.go
Fixes a bug when the request to the template manager fails, causing the build not to cancel and the CLI to remain stuck indefinitely.
<details open>
This PR handles failed connections to the template manager during the build process, ensuring that the build is canceled properly and the CLI does not remain stuck indefinitely.
<details>
```mermaid
participant Handler
participant BuildCache
participant DB
participant Telemetry
Note over Handler: Template Build Error Occurs
Handler->>Telemetry: Report Critical Error
Handler->>DB: Set Build Status to Failed
alt DB Error
DB-->>Telemetry: Report Critical Error (DB)
end
Handler->>BuildCache: Append Build …
```
=> Handle failed connection to template manager during build

packages/template-manager/internal/build/rootfs.go
If the docker image is big (as Code interpreter one) it can take a minute (maybe even several) and there could be not logs.
<details open>
This PR adds logging for the process of pulling a Docker image during the build process, providing feedback on the status of the image pull.
<details>
```mermaid
participant BuildLogsWriter
participant Rootfs
participant DockerSystem
Rootfs->>BuildLogsWriter: Write("Pulling Docker image...")
Rootfs->>DockerSystem: pullDockerImage()
alt successful pull
DockerSystem-->>Rootfs: image pulled
Rootfs->>BuildLogsWriter: Write("Pulled Docker image.")
else error
DockerSystem-->>Rootfs: error
Rootfs-->>BuildLogsWriter: error …
```
=> Add logs for pulling docker image during build

packages/cluster/scripts/start-client.sh
Envd is used only during build, which isn't high volume, is also quite small, and changes often. 
Other option would be to set reasonable ttl for this bucket
<details open>
This PR removes the `--config-file $fuse_config` option from the `gcsfuse` command in the `start-client.sh` script.
<details>
```mermaid
participant Filesystem
participant GCSBucket
Client->>Filesystem: Create directory "/fc-envd"
Client->>GCSBucket: Mount "${FC_ENV_PIPELINE_BUCKET_NAME}"
GCSBucket-->>Filesystem: Mount as read-only with mode 755
Note over Filesystem: Bucket mounted at /fc-envd
```
</details>
<details>
<summary><b>Files Changed</b></summary> …
=> Don't cache envd

packages/api/internal/cache/templates/cache.go, packages/api/internal/handlers/sandbox_create.go, packages/shared/pkg/db/envs.go
<details open>
This PR improves error handling for template retrieval by returning specific errors for not found templates and adjusting error reporting in the API handler.
<details>
```mermaid
participant Handler
participant Cache
participant DB
Client->>Handler: Request template (aliasOrEnvID)
Handler->>Cache: Get(aliasOrEnvID)
alt Cache miss
Cache->>DB: GetEnv(aliasOrEnvID)
alt Template not found
DB-->>Cache: NotFound error
Cache-->>Handler: APIError(404, "template not found")
Handler-->>Client: 404 Status + Error message
else Other DB error
DB-->>Cache: Error
Cache-->>Handler: APIError(500, "error while getting template") …
```
=> Return correct errors for not found template

packages/api/main.go, packages/shared/pkg/gin_utils/middleware/otel/metrics/config.go, packages/shared/pkg/gin_utils/middleware/otel/metrics/middleware.go, packages/shared/pkg/gin_utils/middleware/otel/metrics/otelrecorder.go
This will allow us to set alerts for error rate and set up alert once the requests get slow hence we should know of some problems earlier than when everything goes bad
<details open>
This PR adds metrics to monitor error rates and request durations, enabling alerts for performance issues.
<details>
```mermaid
participant GinRouter
participant MetricsMiddleware
participant OtelRecorder
participant OpenTelemetry
Client->>GinRouter: HTTP Request to /sandboxes
GinRouter->>MetricsMiddleware: Process Request
MetricsMiddleware->>MetricsMiddleware: Start Timer
MetricsMiddleware->>GinRouter: Continue Request Chain …
```
=> Add metrics to allow us set up alerts for error rate and slowing requests

.env.template, self-host.md
Improve the self-hosted guide for GCP. Changed the following:
- `make migration` should be `make migrate`
- Missing variables in .env.template
```
API_MACHINE_TYPE=
API_CLUSTER_SIZE=
```
- Improve Nomad UI link highlighting
=> Improve self-hosted GCP guide

packages/api/main.go, packages/orchestrator/cmd/mock-snapshot/mock.go, packages/orchestrator/main.go, packages/shared/pkg/db/client.go, packages/shared/pkg/telemetry/otel.go, packages/template-manager/main.go
This pulls out part of #237 for extra clarity.
=> shared(api): context infrastructure plumbing for shared packages

packages/api/internal/dns/server.go, packages/api/internal/orchestrator/cache.go, packages/api/internal/orchestrator/orchestrator.go
This is another task pulling a part of #245. 
This presupposes a specific solution (e.g. making redis be the backing (or extra layer) of the routing table/dns records.) but I wanted to avoid mixing "add contexts" from other changes, as this is a very simple PR mechanically despite that touches more lines than (perhaps) it should.
=> chore: plumb contexts to DNS methods

packages/nomad/api.hcl, packages/nomad/main.tf, packages/nomad/redis.hcl
This pulls from #245 but moves the redis service off of the same machines as the API service and onto a separate machine that can be accessed from different services.
This is pretty primitive, but good to keep is separate from changes to the API server code.
Currently, there is only one API server so the previous approach is to colocate the redis server and the API server would work, but wouldn't as soon as we had more than one machine running the API service. I'm also not sure that if we did a rolling restart of the API service (with one instance,) if it would necessarily continue to run on the same host. Regardless someone with more broad context for nomad and our nomad deployment might be more well suited to ironing these details out.
Apart from this we are discussing if we want to run …
=> nomad: add configuration for deploying redis service

packages/api/main.go, packages/shared/pkg/logging/collector.go, packages/shared/pkg/logging/logger.go
I stumbled across these logging issues as I was working, and thought it was easier to push a small patch than outline them in another way. 
The time format defined in the logging encoders was RFC3339 (or equivalent given that it was always UTC.) and there's already a library function for this operation.
I didn't change [this occurance](https://github.com/tychoish/infra/blob/logging-formatting-cleanup/packages/api/internal/handlers/sandbox.go#L105) which appears to mostly be for human consumption (and therefore the extra spaces are desireable. Having said that, this almost certianly should be coerced into UTC.)
=> api(minor): clean up several logging related oddities

packages/orchestrator/internal/sandbox/block/cache.go
Flushing mmap with prot "unix.PROT_EXEC" doesn't flush the bytes to the filesystem file. This PR is trying to address that.
Size of sparse file on disk can be verified using command `du fileName` in build cache. Manually tested by successful start of a new sandbox.
=> Fix mmap flush to the filesystem

packages/orchestrator/internal/sandbox/block/cache.go
Prevent the ability to call read/write methods on already closed block cache in orchestrator, as it might cause invalid reads/writes. This might be simulated by closing the build cache right after creation while fetchToCache is still running.
=> Prevent closed block cache usage

packages/nomad/api.hcl, packages/nomad/main.tf
This allows to start more (1) instances of API server at the same time, it will wait till the new API server is healthy and then send `SIGTERM` signal to shutdown gracefully.
=> Update stanza for API job

packages/envd/internal/host/sync.go
In some distributions there isn't `bash` on `/usr/bin/bash` and `date` on `/usr/bin/date` which resulted in not syncing
=> Fix clock sync on start of the sandbox

Makefile
These are small changes that I made while working that I thought might be useful for other people: 
- moved the `cluster-disk-image-build` task into the `init` target (this changes very rarely, rebuilding it explicitly when needed is safe as the build happens on the remote end.)
- created targets for `build/<package>` and `build-and-upload/<package>` so that we can just build only the component that we need when doing testing.
- made `build-and-upload` work through make's dependency system, so now you can run `make -j<n> build-and-upload` and make will attempt to build and upload in parallel. This off by default, and it's easy to overwhelm a system with these kinds of builds, _but_, if you have extra compute capacity on your local machine.... it makes things quicker.
=> minor: build improvement for make targets

packages/cluster/scripts/run-consul.sh
Without this all services stays in consul and then DNS resolving is returning all nodes where the service ran.
Reproduce:
If you have multiple nodes and redeploy there will be multiple tasks for that service in consul, what's weird they stay healthy
=> Add service permissions to deregister service

packages/shared/migrations/20250205180205.sql
This PR adds a new migration file (`20250205180205.sql`) to the infrastructure repository to centralize our database migrations. The changes introduced by this migration will initially only be utilized in the dashboard repository.
After applying migration `20250205180205.sql`, verify:
- Teams Table Structure:
- New column `slug` added
- Data type: text
- Not nullable
- Has unique constraint
- New column `profile_picture_url` added
- Data type: text
- Nullable allowed
- Unaccent extension is installed
- `generate_team_slug()` function exists and handles:
- Special character removal
- Accent removal
- Email address parsing
- Lowercase conversion
- Space to hyphen conversion
- `generate_team_slug_trigger()` function exists
- Trigger `team_slug_trigger` is active on teams table
- All existing …
=> E2B-1536: move team slug & profile migrations to infra

packages/orchestrator/internal/sandbox/block/cache.go
This PR corrects the ordering of dirty blocks in exporting the root filesystem. It is used to generate diffs during snapshot creation.
=> Fix rootfs blocks order in diffs

packages/nomad/logs-collector.hcl, packages/nomad/loki.hcl
- temporarily stop using app log timestamp and revert back to using Loki ones in logs collector 
- toggling [this flag](https://grafana.com/docs/loki/next/configure/#accept-out-of-order-writes) to allow out-of-order wirtes in Loki 
- increase the maximum accepted sample age before rejecting in Loki. 
- make plan & make apply
- spawn a sandbox
- get sandbox logs and metrics
=> More lenient Loki config and stop timestamp manipulation

packages/api/internal/handlers/sandbox_logs.go, packages/api/internal/handlers/sandbox_metrics.go
instead of log line timestamp in api logs and metrics handler to go from:
```
[0001-01-01 00:00:00.000Z] INFO  { category: 'default', logger: 'orchestrator', message: 'Sandbox created with - end time: 2025-02-20
19:06:49 +00:00' }
```
to:
````
[2025-02-20 19:02:51.338Z] INFO  { category: 'default', logger: 'orchestrator', message: 'Sandbox created with - end time: 2025-02-20
19:07:51 +00:00' }
```
this is cause by the changes in logs-collector: https://github.com/e2b-dev/infra/pull/314
=> Revert back to using Loki entry timestamp 

packages/api/main.go
Add API server timeouts. The values might need to be adjusted in the future. Right now set to 75 seconds, as the LB timeout is 65 seconds.
(More info: https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/)
=> Add API server timeouts

packages/orchestrator/cmd/inspect-data/main.go, packages/orchestrator/cmd/inspect-header/main.go, packages/orchestrator/cmd/simulate-headers-merge/main.go, packages/orchestrator/internal/sandbox/template/cache.go, packages/shared/pkg/storage/gcs/bucket.go, packages/shared/pkg/storage/gcs/client.go, packages/shared/pkg/storage/template_build.go, packages/template-manager/go.mod, packages/template-manager/go.sum, packages/template-manager/internal/build/network_linux.go, packages/template-manager/internal/build/network_other.go, packages/template-manager/internal/build/rootfs.go, packages/template-manager/internal/build/rootfs_test.go, packages/template-manager/internal/build/snapshot_linux.go, packages/template-manager/internal/build/snapshot_other.go, packages/template-manager/internal/template/storage.go
Looking to test `createRootFS`, so splitting out this routine into its own stuct to test. In order to test this locally on mac need to set build flags for linux. also refactors some behavior in `shared` to be able to run tests
=> Split out and test post processing in template build

packages/orchestrator/go.mod, packages/orchestrator/go.sum, packages/orchestrator/internal/server/main.go
It will log all grpc calls (unary, stream) to the stdout. The logger will have to be changed after the PR with logging is merged.
Logging includes request AND response payloads.
=> Add basic logging of grpc calls to the orchestrator

packages/orchestrator/internal/sandbox/checks.go, packages/orchestrator/internal/server/sandboxes.go
- Remove unused ticker
- Add separate context timeout for healtcheck/metrics before sandbox kill to prevent
- Increase the interval of metrics to check if the flooding and RAM hogging in API is related (we can increase if everything is ok). We should also check the logs exporter implementation to see if the logs can get buffered there.
Related changes (removing stat with uncancelled goroutine) were already introduced via 2af377419058eeae47e4547215bc7ad5bb1298c3
=> Cleanup metrics and temporarily increase the interval

packages/api/internal/handlers/template_start_build.go, packages/api/internal/template-manager/client.go, packages/shared/pkg/grpc/connection.go, packages/template-manager/internal/server/main.go
If the template manager was moved, the connection became stale and building wasn't working
=> Automatically reconnect to newly deployed template manager

packages/shared/pkg/logging/logger.go
We can get our logger by calling `zap.L()`, there's no need to pass it around anymore
=> Set our logger as a global one

packages/orchestrator/internal/sandbox/nbd/dispatch.go, packages/orchestrator/internal/sandbox/nbd/path_direct.go
There is a panic at the Wait() method in dispatch.go. 
The dispatcher might be nil when closing the `DirectPathMount`. This might occur if it errors out before assignment.
Also, the Wait() method might get stuck if pendingResponses are not "0". This should be possible only if the `fatal` channel gets full (8 errors) and no new errors can be inserted. Then it will not decrease pendingResponses and Wait will be deadlocked. This PR will log read/write error instead of filling up the channel (of size 8).
Tries to fix following panic:
`
panic caught: runtime error: invalid memory address or nil pointer dereference goroutine 61569791 [running]: github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery.recoverFrom({0x19da760?, 0xe282d26270?}, {0x14ca120, 0x266a750}, 0xe287286b47?) …
=> Try to fix NBD panic

packages/cluster/build-cluster/main.tf, packages/envd/internal/host/sync.go
The build cluster defaulted to Haswell CPU platform which caused incompatibility when building for Skylake we use elsewhere. It manifested as incorrectly working ptp0 device (so far).
I also added detailed error to the envd sync.
=> Fix build cluster platform

packages/template-manager/internal/build/snapshot_linux.go
Customers require more ram for some templates, this will increase the ram allocation to the max for select template ids
=> Increase ram allocation for select templates

packages/nomad/logs-collector.hcl, packages/shared/pkg/logger/logger.go
Fixes timestamps in sandbox logs, so the timestamp corresponds to the time of creation and not the time of http sent.
=> Fix sandbox logs timestamps

packages/orchestrator/internal/sandbox/checks.go, packages/orchestrator/internal/sandbox/sandbox.go
- If not we would report the first health check as a change in the status
- Runs the initial sandbox health check
=> Set sandbox healthy status to true by default

packages/api/internal/handlers/store.go
Break was "caught" by select, resulting in infinite cycle
=> Fix break in initial health loop in API

packages/api/internal/cache/instance/lifecycle_cache.go, packages/api/internal/cache/instance/lifecycle_cache_test.go, packages/api/internal/cache/instance/operations.go
Fixes synchronization issue between orchestrator sandboxes state and API cache state. This change will check in the exists method also for items that are being evicted, so they won't be added while the eviction is happening.
=> Fix cache eviction and sync node synchronization

packages/api/internal/handlers/sandbox_pause.go, packages/api/internal/handlers/sandbox_resume.go, packages/shared/pkg/db/errors.go, packages/shared/pkg/db/snapshot.go
It's little bit annoying with `entgo`, I have to get back to the conversion to `sqlc`.
But to the point, the original query was pulling all env_builds and joining them in memory. Now there should be only 3 queries, each fetching only 1 record 
```sql
SELECT "public"."snapshots"."id", "public"."snapshots"."created_at", "public"."snapshots"."base_env_id", "public"."snapshots"."env_id", "public"."snapshots"."sandbox_id", "public"."snapshots"."metadata" FROM "public"."snapshots" WHERE "public"."snapshots"."sandbox_id" = $1 LIMIT 2 args=[<sandbox ID>]
SELECT "public"."env_builds"."id", "public"."env_builds"."created_at", "public"."env_builds"."updated_at", "public"."env_builds"."finished_at", "public"."env_builds"."env_id", "public"."env_builds"."status", "public"."env_builds"."dockerfile", …
```
=> Optimize DB queries for pause / resume

packages/api/internal/handlers/template_build_logs.go, packages/api/internal/template-manager/create_template.go, packages/nomad/logs-collector.hcl, packages/template-manager/internal/build/rootfs.go, packages/template-manager/internal/build/rootfs_test.go, packages/template-manager/internal/build/writer/writer.go, packages/template-manager/internal/server/create_template.go, packages/template-manager/internal/server/main.go, packages/template-manager/main.go
Template build logs are pushed to Loki and API is using Loki directly to query them for user instead of local API cache.
**[Deploy]**
First template manager needs to be rolled so it will push logs to logger and also for back compatibility via grcp stream. Later api can be rolled later, there are no user-facing changes here or come breaking one.
=> Remove template logs from API cache

packages/orchestrator/internal/server/sandboxes.go
If error is returned, sbx is `nil`
=> Fix nil dereference

.github/actions/start-services/action.yml, packages/orchestrator/Makefile, packages/orchestrator/internal/sandbox/sandbox.go
Adds a variable for envd timeout. The default is 10s when not set. It is used in the integration testing, there it's set to 60s.
=> Make envd timeout a variable

packages/shared/pkg/db/snapshot.go
When there's problem with creating new transaction (connection pool exhausted?) handle the error
=> Handle error when creating transaction

packages/orchestrator/internal/sandbox/envd.go
there was bug when reader is provided to request loop that is trying to initialize envd but because its not running yet, some requests can fails. Reader buffer provided with JSON request body was read in first round that failed and later it was empty so envd service initialized with empty body, that means without environments.
=> fixed empty reader buffer after second try of calling envd init endpoint

packages/nomad/clickhouse.hcl, packages/nomad/main.tf, packages/nomad/variables.tf
This change adds clickhouse and corresponding gcs bucket and permissions for clickhouse to access the bucket to our nomad cluster
=> Deploy clickhouse on nomad

packages/api/internal/cache/instance/instance.go, packages/api/internal/cache/instance/monitoring.go, packages/api/internal/cache/instance/operations.go, packages/api/internal/cache/instance/sync.go, packages/api/internal/orchestrator/analytics.go, packages/api/internal/orchestrator/cache.go, packages/api/internal/orchestrator/create_instance.go, packages/api/internal/orchestrator/orchestrator.go
Linear issue + parent issue description.
This PR should improve analytics reporting. It should do it async in the creation/deletion cases, and synchronously in the SyncNodes case.
Also, it changes the sync nodes interval back to 3 minutes (from 20 seconds).
=> Improve analytics reporting in the API

tests/periodic-test/internet-works.ts
We can change the endpoint we are checking so we are not reporting sandbox * [e2b.dev](http://e2b.dev/) availability this way? :D
=> Use google.com instead of e2b.dev to test internet connectivity

packages/api/main.tf, packages/nomad/main.tf
if you run make plan on main you will get an error
```
var.clickhouse_password
The password for the ClickHouse database
Enter a value: f
╷
│ Error: Reference to undeclared resource
│ 
│   on packages/nomad/main.tf line 423, in resource "nomad_job" "clickhouse":
│  423:     password_sha256_hex = sha256(random_password.clickhouse_password.result)
│ 
│ A managed resource "random_password" "clickhouse_password" has not been declared in module.nomad.
╵
make: *** [Makefile:58: plan] Error 1
➜  infra git:(fix-clickhouse-bug)     
```
but this changes fixes
```
infra git:(fix-clickhouse-bug) make apply                                                                                                                                                          ~/infra
Applying Terraform for env: dev …
```
=> Use var instead of random_password since we moved that resource

packages/orchestrator/internal/sandbox/build/cache.go, packages/orchestrator/internal/sandbox/build/diff.go, packages/orchestrator/internal/sandbox/build/local_diff.go, packages/orchestrator/internal/sandbox/build/storage_diff.go
The https://github.com/e2b-dev/infra/pull/253 introduced a bug by using wrong build cache key when creating snapshots. This PR fixes the cache key and adds a bit of refactor to prevent the same bug in the future.
The issue could be simulated using the following steps:
1) start sandbox
2) pause sandbox
3) ...sandbox files are uploading to GCP, but not in the build cache (because of the wrong key)
4) resume sandbox
5) cache miss, trying to download from GCP, but nothing is yet in GCP -> error
=> Fix build cache key for snapshots

packages/shared/Makefile
Under `/packages/shared/Makefile` we have a command prep-cluster which is also mentioned in `self-host.md`. the referenced go file was missing, which is fixed by this pr.
=> Fix reference to correct go file for seeding database on prep-cluster

packages/api/internal/orchestrator/node.go
Fixes status reporting when grpc is in IDLE status. Right now, if the node goes to the IDLE state (no requests for longer time), no new sandboxes could be created and the state doesn't change back.
=> Fix gRPC idle status reporting

main.tf, packages/nomad/main.tf, variables.tf
Clickhouse needs some environment variables to be set in order to connect to the database. We need to set them but they are static and not secret. The password is also generated by terraform. This removes the top level variables so that the programmer does not have to include configuration to deploy clickhouse
=> Connect clickhouse client to clickhouse deployment

main.tf, packages/api/outputs.tf, packages/nomad/main.tf, packages/nomad/variables.tf
using data to access secrets creates data races, instead lets plumb the data through to avoid that
=> Refactor Supabase JWT secret handling in Nomad and API modules

packages/shared/pkg/db/envs.go, tests/integration/seed.go
`.Only()` overrides `Limit`, so it will change `Limit` to 2 and then raise an error if there's more builds present
=> Fix bug when template has multiple builds

packages/cluster/network/main.tf
- Client proxy health endpoint is the only service with different port for health check
- You can still SSH via GCP console, but you can't connect directly from command line (you would need to add your personal IP)
**Allow**:
- For internal IPs for 22 and 3389 (remote desktop access) - prio 900 (all ips if dev)
**Deny**: 
- All access for 22 and 3389 (remote desktop access) - prio 1000
- Access for not needed ports
=> Limit public access to our VM ports

.golangci.yml
Fixes the following deprecations:
The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.
The linter 'tenv' is deprecated (since v1.64.0) due to: Duplicate feature in another linter. Replaced by usetesting.
=> Fix GoLint deprecations

main.tf, packages/client-proxy/main.go, packages/nomad/main.tf, packages/nomad/orchestrator.hcl, packages/nomad/variables.tf, packages/orchestrator/cmd/mock-sandbox/mock.go, packages/orchestrator/cmd/mock-snapshot/mock.go, packages/orchestrator/internal/proxy/proxy.go, packages/orchestrator/internal/proxy/proxy_browser_502.html, packages/orchestrator/internal/sandbox/sandbox_linux.go, packages/orchestrator/internal/sandbox/sandbox_other.go, packages/orchestrator/internal/server/main.go, packages/orchestrator/internal/server/sandboxes.go, packages/orchestrator/main.go, packages/shared/pkg/meters/main.go, variables.tf
Implements http proxy in orchestrator that replaces current nginx-based session proxy that is using dns server from orchestrator to route traffic.
- Legacy Nginx session-proxy is intact and can still be used as it is, next step will be remove it when traffic migrated
- Orchestrator proxy for now runs on port `5007` allowing smooth deployment
- Support for pretty (for browsers) and json error messages when port in sandbox not listening
- Proxy settings is taken from currently used client-proxy, so should be already battle-tested
=> Replace Nginx based session proxy with orchestrator proxy

packages/api/internal/handlers/template_start_build.go, packages/api/internal/template-manager/template_manager.go
If database call takes long enough it's possible to finish build successfully and if you immediately try to spawn a sandbox with this template, it's possible it will return 404, because it isn't propagated in DB yet
=> Fix race condition in the template manager

packages/nomad/loki.hcl
From the Loki Grafana it seems that part of the memory problems with the current Loki setup is because of the number of retained chunks. These can be failed chunks in several cases though, so I think we first need to find stable Loki configuration.
The next step would be adding scaling/moving the data to other DB (clickhouse?).
We also disabled `wal` which normally helps with replaying the previous unprocessed traffic, but with our job placement it does not make sense now.
=> Lower Loki chunk retention and ttls

go.work.sum, packages/api/main.go, packages/client-proxy/main.go, packages/orchestrator/go.mod, packages/orchestrator/go.sum, packages/orchestrator/internal/server/healthcheck.go, packages/orchestrator/internal/server/main.go, packages/orchestrator/main.go, packages/shared/pkg/meters/main.go, packages/shared/pkg/telemetry/otel.go, packages/template-manager/main.go
Adds:
- HTTP Endpoint "/health" reporting 
```
{
"status": "healthy",
"version": "6fe34854"
}
```
- Orchestrator count metric (async updown counter) "orchestrator.env.sandbox.running"
- OTEL InstanceID
=> Add basic orchestrator healthcheck

.github/actions/start-services/action.yml, packages/orchestrator/internal/server/healthcheck.go, scripts/start-service.sh
Await healthy services in the integration tests based on healthcheck (/health endpoint) and not just sleeping fixed amount of seconds. This also speeds up the tests total time.
=> Wait for services healthcheck instead of sleep

packages/api/internal/template-manager/template_manager.go, packages/api/internal/template-manager/template_manager_test.go
the inner polling loop behaves like this 
```
if err != nil && strings.Contains(err.Error(), "context deadline exceeded") {
return errors.Wrap(err, "context deadline exceeded")
} else if err != nil { // retry only on context deadline exceeded
return retry.Stop(errors.Wrap(err, "error when polling build status"))
}
```
which the outer polling loop receives like this 
```
err := retrier.Run(c.setStatus)
if err != nil {
return errors.Wrap(err, "error when polling build status")
}
```
which would result in polling for errors that should be stopped from the inner loop from the outer loop. This changes adds a check for terminal errors to bubble up the callstack and stop the outer loop from the inner loop and tests for this behavior
=> Fix bug for outer retry will eat  inner retry.stop error and continue instead of stopping bug for template manager api polling logic

.github/workflows/integration_tests.yml
Retry integration tests on fail (3 times max) to prevent flakiness with the EOF error
=> Retry integration tests on fail

packages/api/internal/template-manager/template_manager.go, packages/api/internal/template-manager/template_manager_test.go
Before, when template manager was killed, the outer loop would continue to retry because the retry.Stop error was not returned in the proper scope. 
This change moves that logic to the proper scope so that we don't continue to retry when we reach a terminal state. 
tested by deploying to local cluster, running a build and killing template-manager job. 
logs: 
```
2025-03-24 14:29:49.803 | Setting template build status |  
-- | -- | --
  |   | 2025-03-24 14:29:49.695 | Template build info found in cache |  
  |   | 2025-03-24 14:29:49.456 | Polling timed out |  
  |   | 2025-03-24 14:29:49.456 | got terminal error when polling build status |  
  |   | 2025-03-24 14:29:49.455 | error when calling setStatus |  
  |   | 2025-03-24 14:29:49.455 | terminal error when polling build status |  
  …
```
=> Handle retry error in correct scope

main.tf, packages/api/internal/template-manager/client.go, packages/nomad/main.tf, packages/nomad/template-manager.hcl, packages/nomad/variables.tf, packages/orchestrator/main.go, packages/template-manager/internal/server/main.go, packages/template-manager/main.go
Adds safe shutdown for template manager that waits for all jobs to be finished. Adds kill timeout for template manager service in nomad.
Currently depends on https://github.com/e2b-dev/infra/pull/508 to remove cherry picks from this PR.
=> Shutdown logic for template manager

packages/api/main.go, packages/nomad/otel-collector.hcl
Adds metrics for pause and resume in the API, and for all grpc methods in the orchestrator.
=> Add metrics for pause and resume endpoints

.github/actions/deploy-setup-staging/action.yml
Increase API and build cluster size for staging environment to allow no-downtime rolling updates
=> Increase staging cluster sizes to allow rolling updates

.github/actions/build-packages/action.yml, .github/actions/host-init/init-client.sh
Currently there is copy paste of already build envd from our public bucket, 
but in case we want to test changes in envd itself we should
build it ourself in every integrations tests run.
=> Build and use envd for integration tests

packages/api/main.go, packages/orchestrator/cmd/mock-nbd/mock.go, packages/orchestrator/cmd/mock-sandbox/mock.go, packages/orchestrator/cmd/mock-snapshot/mock.go, packages/orchestrator/internal/sandbox/cleanup.go, packages/orchestrator/internal/sandbox/nbd/path_direct_linux.go, packages/orchestrator/internal/sandbox/rootfs/cow.go, packages/orchestrator/internal/sandbox/sandbox_linux.go, packages/orchestrator/internal/server/sandboxes.go
Adds traces (by passing context) for sandbox cleanup. This is to here help debug pause taking long time. 
This PR also adds monitoring of /sandboxes/:sandboxID for monitoring "kill" execution time.
=> Improve traces logging for cleanup

self-host.md
In favor of the new google secret for supabase jwt authentication headers on the api, we should update our self hosting guides and let users know that the google secret is required for dashboard hosting.
RFC: In my opinion we should keep the impact of this as minimal as possible, as long as we are not fully committed to this authentication approach. Since the dashboard self-hosting guide refers to this repository for self-hosting the infrastructure first, and to keep the impact minimal, i would suggest only mentioning the setup for this here. 
Thoughts?
=> Update self-host.md to account for new jwt auth mechanism

packages/client-proxy/main.go, packages/orchestrator/internal/proxy/proxy.go
In SDK we expect error with field `message` not `error`:  https://github.com/e2b-dev/E2B/blob/main/packages/js-sdk/src/envd/api.ts#L28
=> Fix error message in proxies

packages/client-proxy/main.go
Client cache is currently targetting nginx sandbox cache that has already disabled keep alive, same with new not yet used orchestrator cache that is also configure without keep alive.
This should fix expectations of client proxy to communicate with already closed connections, because keep alive is disabled in both nginx-based session and orchestrator proxies.
=> Disabled keep alive on client proxy cache

terraform/redis/main.tf
Remove sharding for the managed Redis cluster, because we should not need it right now and add replication instead.
=> Remove managed Redis sharding and add replication

packages/template-manager/internal/build/provision.sh, tests/integration/internal/tests/envd/filesystem_test.go
if a user includes the following line in their  Dockerfile 
```
RUN chmod 666 -R /home/user/app
```
these  permissions are overwritten by the following line later in our provision.sh script 
```
chmod 777 -R /home/user
```
This change prevents this from happening while retaining user ownership of files copied into that directory using a flow similar to the following 
```
FROM python:3.12-slim 
RUN mkdir -p /home/user 
COPY startup.sh /home/user/startup.sh
```
=> Use chown of chmod for user home dir to fix permission and ownership issues

packages/api/internal/handlers/sandboxes_list.go, tests/integration/internal/tests/api/sandbox_list_test.go
Sorting was removed by accident during introduction of the new sandbox list endpoint
=> Return sorting to sandbox list

packages/nomad/otel-collector.hcl
Fixes rpc server duration metric logging. For some reason it doesn't work with `_`, but it works with any char (`.`), so I'm using that.
=> Fix RPC server duration metric

packages/nomad/otel-collector.hcl
Remove instance from the rpc_server_duration metric, which should reduce the cardinality by the factor of 16
=> Reduce rpc_server_duration metric cardinality

.github/workflows/deploy-infra.yml, .github/workflows/deploy-job.yml
Add input to only plan the terraform configuration, not actually applying it. This is to verify that the plan is correct.
=> Allow only plan the deployment

packages/api/internal/handlers/sandbox_create.go, packages/api/internal/middleware/otel/metrics/middleware.go
Improves observability of startup times of specific templates.
- base
- code-interpreter-v1
- code-interpreter-beta
- desktop
=> Add template alias attribute to gin middleware metrics

packages/api/internal/handlers/template_build_status.go
If loki crashes, it shouldn't fail build, especially if the build is still running in the background.
=> Don't fail build on missing logs

packages/api/main.go
E.g. for incorrectly passing parameter multiple times (exploded) instead of only separated by comma, we are returning following response
```json
{"msg":"Invalid format for parameter state: parameter 'state' is not exploded, but is specified multiple times"}
```
But SDK expects the error to have field `message`.
After passing our error handler, we return following error
```json
{"code":400,"message":"validation error: Invalid format for parameter state: parameter 'state' is not exploded, but is specified multiple times"}
```
This was causing for some validation errors to be logged as:
```
SandboxError: 400: [object Object]
```
in JS SDK.
=> Fix error message type for validation

packages/template-manager/internal/build/rootfs.go
Increase memory for the part of the build when exporting rootfs
Before this change:
```
error | error creating rootfs for env 'ffj7ru56ykc5yfcflniu' during build 'ee6830b4-dd2f-4e6c-aa66-b14f91d8ab32': error creating rootfs file: container exited with status 137:
```
After I was able to build the template and start it:
```sh
~ E2B_DOMAIN=krindapana.dev e2b sbx sp ffj7ru56ykc5yfcflniu
Terminal connecting to template ffj7ru56ykc5yfcflniu with sandbox ID ildfkac242oujw2ntorzm-447dc250
user@d40650b7c9d8:~$ free -h
total        used        free      shared  buff/cache   available
Mem:           106Mi        59Mi       5.3Mi       936Ki        51Mi        47Mi
Swap:          127Mi          0B       127Mi
user@d40650b7c9d8:~$ 
```
=> Increase memory during build when memory for the template is small

packages/envd/internal/services/filesystem/stat.go
Fixes missing property `Path` when calling `Stat`
=> Fix missing property in filessystem stat

packages/envd/internal/services/filesystem/watch.go, packages/envd/internal/services/process/connect.go, packages/envd/internal/services/process/input.go, packages/envd/internal/services/process/start.go
We pass most of the envd unknown errors without wrapping the message which can be confusing on client as we cannot be sure where the error originated—on client/server and at what part of the envd request handling.
=> Add more info to the unknown envd errors

packages/envd/internal/services/process/handler/handler.go, packages/envd/internal/services/process/start.go
- Cleanup handler initialization
- Fix output context cancellation—prevent race condition with the whole process context
- Ensure the process cancel is not overriding what signal is propagated when forwarding signals to the process
=> Fix race conditon between process cancellation and pipe closing

terraform/grafana/stack/panels/sandbox-pause-errors-old.json, terraform/grafana/stack/panels/sandbox-pause-latency-old.json
Changes source of pause error traces from the HTTP to the orchestrator ones in the chart
=> Improve graph for pause error traces

packages/api/internal/cache/instance/lifecycle_cache_test.go
Improves flakiness of a `TestLifecycleCacheHasEvicting` unit test where the channel might have ended sooner than the evicting map deletion
=> Improve lifecycle cache unit test flakiness

tests/integration/internal/main_test.go
Prevent segmentation fault and improve logs when running TestCacheTemplate integration test
=> Improve integration test logs

tests/integration/internal/setup/envd_client.go, tests/integration/internal/tests/envd/auth_test.go
If the envd init request in integration tests fail we get and print the envd logs so we can inspect what happened.
=> Print envd logs on integration test envd init fail

.github/workflows/deploy-infra.yml
After installing goose, it still can't be found, because gopath isn't set. Setting up go before fixes the issue
=> Fix missing "goose" during deployment when running `make migrate` 

packages/template-manager/cmd/build-template/main.go, tests/integration/internal/setup/constants.go, tests/integration/internal/setup/envd_client.go, tests/integration/internal/tests/envd/process_test.go, tests/integration/internal/utils/sandbox.go
Add test for killing NextJs process, and command `first && second`, and listing the running processes right after kill. 
Note: I needed to increase the memory and disk size for the base (built in integration tests) template, as well as sandbox and http client timeouts, to be able to handle these tests.
Prevents regression for https://github.com/e2b-dev/infra/pull/472
=> Add kill process test

packages/orchestrator/internal/sandbox/build/cache.go
Don't fail if the size get fails on remaining space eviction. The file size is used only as a estimate and doesn't have real meaning for removing the diff from the cache.
=> Don't fail on remaining space eviction

.github/actions/build-packages/action.yml, .github/actions/build-sandbox-template/action.yml, .github/actions/host-init/action.yml, packages/db/Makefile, tests/integration/internal/main_test.go
Fixes integrations tests failing by creating a new build id each tests run to not interfere with other integration test runs.
=> Create new build id for each integrations test run

.github/workflows/push-main.yml
Run all unit and integration tests on the main branch push. This (apart from testing each commit), should give us shared cache for dependencies and build for each newly created branch/PR.
=> Run test on main branch push

packages/cluster/scripts/start-client.sh
If we use too much memory, the orchestrator node might not be able to allocate huge pages anymore because the memory is too fragmented.
=> Increase the initial huge pages ratio

packages/db/migrations/20250506112836_builds_status_index.sql
As we save snapshots to sandbox builds, there's a growing number of rows in the table, which makes some queries slow (e.g., listing all running builds). Adding an index on status will help with this.
=> Add index for build status

packages/shared/pkg/logger/logger.go, packages/shared/pkg/logger/sandbox/logger.go
Disables stacktraces for external logger. It isn't very useful to the users and also unreadable in CLI
=> Disable stacktraces for external loggers

packages/envd/main.go
The lower read header timeout and too big idle timeout can cause problems with our setup.
- https://github.com/golang/go/issues/47007
=> Reconfigure timeout in envd

packages/api/main.go, packages/client-proxy/internal/proxy/proxy.go, packages/cluster/network/main.tf, packages/orchestrator/internal/proxy/proxy.go, packages/shared/pkg/proxy/proxy.go
The read header timeout lower than the backend timeout and the idle timeout lower than the LB idle timeout can be causing connection problems.
- https://github.com/golang/go/issues/47007
- https://cloud.google.com/load-balancing/docs/https/troubleshooting-ext-https-lbs#troubleshoot_general_connectivity_issues
=> Reconfigure API timeouts

packages/shared/pkg/telemetry/otel.go, terraform/grafana/stack/dashboards/main/panels/sandbox-create-errors.json, terraform/grafana/stack/dashboards/main/panels/sandbox-create-latency-long-term.json, terraform/grafana/stack/dashboards/main/panels/sandbox-create-latency.json, terraform/grafana/stack/dashboards/main/panels/sandbox-kill-errors.json, terraform/grafana/stack/dashboards/main/panels/sandbox-kill-latency-long-term.json, terraform/grafana/stack/dashboards/main/panels/sandbox-kill-latency.json, terraform/grafana/stack/dashboards/main/panels/sandbox-pause-errors-orchestrator.json, terraform/grafana/stack/dashboards/main/panels/sandbox-pause-errors.json, terraform/grafana/stack/dashboards/main/panels/sandbox-pause-latency-orchestrator.json, terraform/grafana/stack/dashboards/main/panels/sandbox-pause-latency.json, terraform/grafana/stack/dashboards/main/panels/sandbox-resume-errors.json, terraform/grafana/stack/dashboards/main/panels/sandbox-resume-latency.json
Use native exponential buckets for histograms.
More information about native exponential buckets:
https://grafana.com/blog/2025/05/06/prometheus-native-histograms-in-grafana-cloud-more-precise-easier-to-use-and-better-compatibility
As this PR changes the usage to native buckets and updates Grafana panels, old data won't be shown anymore.
=> Use native exponential buckets for histograms

packages/orchestrator/internal/sandbox/nbd/path_direct_linux.go
Fixes:
```
goroutine [running]:
github.com/e2b-dev/infra/packages/orchestrator/internal/sandbox/nbd.(*DirectPathMount).Open()
/build/orchestrator/internal/sandbox/nbd/path_direct_linux.go:160
panic: runtime error: invalid memory address or nil pointer dereference
```
=> Fix nil dereference when checking error while connecting to NDB

packages/api/internal/template-manager/template_manager.go, packages/shared/pkg/db/snapshot.go, packages/shared/pkg/models/envbuild/envbuild.go, packages/shared/pkg/models/migrate/schema.go, packages/shared/pkg/schema/build.go
There is a race condition with template manager checking old builds, which can mark the snapshot as failed
=> Use separate status for snapshots

packages/api/internal/auth/middleware.go, packages/api/internal/cache/auth/cache.go, packages/api/internal/handlers/store.go, packages/api/internal/utils/error.go, packages/shared/pkg/db/apiKeys.go
Return better error when team is blocked or banned.
```
{
"code": 403,
"message": "Forbidden: team was blocked, reason: didn't use e2b enough"
}
```
instead of
```
{
"code": 401,
"message": "Invalid API key, please visit https://e2b.dev/docs/quickstart/api-key for more information."
}
```
=> Better error for blocked teams

packages/client-proxy/internal/proxy/proxy.go, packages/nomad/client-proxy.hcl, packages/orchestrator/internal/proxy/proxy.go, packages/shared/pkg/proxy/pool/pool.go, packages/shared/pkg/proxy/proxy.go, packages/shared/pkg/proxy/proxy_test.go
Because the HTTP pipelining is disabled, there is not much reason to split pools and enforce minimum connections.
This PR also sets Docker ulimit for the client-proxy via Nomad.
=> Remove proxy pool min connection enforcement

packages/shared/pkg/proxy/pool/client.go
It seems that the `SetXForwarded` setting of `X-Forwarded-Proto` header for `http` might be affecting user functionality—some services like Expo are returning unexpected `content-location` starting with `http://` then.
We need to check if the `X-Forwarded-Proto` really does this and if so deploy this fix in client-proxy and orchestrators.
=> Disable `SetXForwarded` to prevent servers returning unexpected `content-location`

packages/shared/pkg/proxy/pool/client.go
There's extra string added to the error coming from orchestrator proxy
Also I don't think should be altering errors coming from sandboxes
JSON:
```json
{
"sandboxId":"iskokv1sjax752ysoylqj",
"message":"The sandbox is running but port is not open",
"port":3000,
"code":502
}Failed to route request to sandbox\n'
```
HTML:
=> Remove the extra message appended to the error coming from backend

packages/db/migrations/20250513111201_tier_fix_max_memory.sql
Set to 8096 instead of 8192, bad math
=> Fix max memory default migration

packages/api/internal/handlers/admin.go, packages/api/internal/orchestrator/cache.go, packages/api/internal/orchestrator/client.go, packages/api/internal/orchestrator/node.go
- currently there was just per-api health status adjustment
- this new thing now requests status change on orchestrator itself and waits for propagation via node sync
=> API: Request to node status will send status change to the orchestrator

tests/periodic-test/time-is-synchronized/index.ts
Fix periodic tests start cmd by escaping the argument
=> Fix periodic tests start cmd

terraform/grafana/stack/dashboards/main/panels/orchestrator-nodes-disk-cache.json
=> Fix the filter in grafana dashboard for orch cache disk

packages/orchestrator/cmd/build-template/main.go, packages/orchestrator/internal/sandbox/network/pool.go, packages/orchestrator/internal/sandbox/network/storage.go, packages/orchestrator/internal/sandbox/network/storage_kv.go, packages/orchestrator/internal/sandbox/network/storage_local.go, packages/orchestrator/internal/sandbox/network/storage_memory.go, packages/orchestrator/main.go
- Local-only implementation of network namespaces acquire that is safe to run on not clean environments.
- During startup checks all already create namespaces and adds them into foreign "block list" to skip them.
- When available namespace is found it will test if its really not existing (was not created during program lifetime).
Notes:
- Acquire is infinite loop with context timeout set to 5 seconds. We should lower it, will check that.
- When acquire function will find empty namespaces but then its marked as available maybe we should also put it into map and fast-skip it later.
=> Orchestrators network namespaces safe-acquire

packages/cluster-disk-image/setup/install-nomad.sh, packages/cluster/scripts/run-api-nomad.sh, packages/cluster/scripts/run-build-cluster-nomad.sh, packages/cluster/scripts/run-nomad.sh
'local readonly' makes a variable called "readonly" local, which isn't actually what we want to have happen here.
To be clear, my IDE warned me of this (thanks to shellchecks' [SC2316](https://github.com/koalaman/shellcheck/wiki/SC2316) warning). I did throw together a demo to prove that it was correct:
```bash
#!/usr/bin/env bash
function test1() {
local readonly one=$1
local readonly two=$2
one=$two
echo "test1: that shouldn't have worked"
}
function test2() {
local -r one=$1
local -r two=$2
one=$two    # line 13
echo "test2: that shouldn't have worked"
}
test1
test2
```
When running bash 5.2.37(1) locally, it results in the following output:
```
$ ./test.sh 
test1: that shouldn't have worked
./test.sh: line 13: one: readonly variable
```
Not particularly important in the places it's …
=> make the variables readonly

packages/api/internal/cache/instance/reservation.go, packages/api/internal/cache/instance/reservation_test.go, packages/api/internal/orchestrator/create_instance.go
If you tried to resume a sandbox while it's already resuming it failed and returned 429 incorrectly. Now it returns 409
=> Return a correct status code for resume conflict

packages/orchestrator/internal/template/build/rootfs.go
Fix init path for Debian images. Debian images don't have symlink from /bin -> /usr/bin. Use the /usr/bin directly for the BuxyBox init file.
=> Fix init path for Debian images

packages/orchestrator/internal/sandbox/sandbox_linux.go, packages/orchestrator/internal/template/build/template_builder.go
Increase envd timeout for template build. This might help big templates taking longer time to boot.
=> Increase envd timeout for template build

packages/orchestrator/internal/template/build/provision.sh, packages/orchestrator/internal/template/build/rootfs.go
Fixes envd init with Docker installed. This configures localhost ipv6 and disables `systemd-networkd-wait-online.service`.
The issue was manifesting by getting stuck on systemd await for `systemd-networkd-wait-online.service`.
=> Fix envd start with Docker installed

packages/orchestrator/internal/sandbox/sandbox_linux.go, packages/orchestrator/internal/sandbox/template/local_template.go, packages/orchestrator/internal/sandbox/template/template.go, packages/orchestrator/internal/template/build/template_builder.go
Delete diff files after template build. This is not done in orchestrator as we want to reuse the artifacts from pause for resume.
=> Delete diff files after template build

packages/orchestrator/internal/template/build/provision.sh
Fix possible DNS configuration override when installing systemd on certain systems. Manifesting by not working DNS server and being replaced by a symlink.
The fix is done by making the /etc/resolv.conf immutable while running provisioning script.
=> Fix dns configuration override

packages/orchestrator/internal/template/build/ext4/tools.go, packages/orchestrator/internal/template/build/memory.go, packages/orchestrator/internal/template/build/oci/oci.go
Sync files explicitly before the next operation. Close doesn't sync the file metadata and data to be used by other processes like FC or filesystem changes (https://www.reddit.com/r/golang/comments/6gsjlf/dont_defer_close_on_writable_files/). The synchronization is necessary for e.g. resizing the file filesystem properly.
Should help fix the filesystem integrity checks during template build.
=> Sync files explicitly before next operation

tests/integration/internal/tests/api/sandbox_list_test.go, tests/integration/internal/tests/envd/process_test.go, tests/integration/internal/utils/sandbox.go
To prevent cross-contamination during multiple tests, ensure the use of distinct metadata.
=> Improve list tests - Add unique metadata per test

packages/orchestrator/internal/template/build/template_builder.go
Extend provisioning timeout to 5 minutes. This is to help the global ubuntu apt outage ([Reddit](https://www.reddit.com/r/Ubuntu/comments/1kxyig1/anyone_know_what_is_going_on_with_ubuntu_archives/?sort=new))
=> Extend provisioning timeout to 5 minutes

packages/api/internal/handlers/sandbox_kill.go
Delete the snapshots in background, so it isn't blocking kill
Also we don't want to return an error for kill if there's some issue with deleting snapshots
=> Delete snapshots in the background

packages/nomad/clickhouse.hcl, packages/nomad/main.tf
Allows to reference `clickhouse` as `clickhouse.service.consul` or if you need specific node (needed for clickhouse internally) as `server-n.clickhouse.service.consul`
=> Use tags to distinguish between servers

packages/api/internal/template-manager/template_manager.go, packages/api/internal/template-manager/template_manager_test.go
Fix build status handling when the build is in failed status, but completed. Right now if the build is in the failed state, the status is repeatedly requested until it times out.
=> Fix build failed status handling

packages/nomad/logs-collector.hcl, packages/nomad/otel-collector.hcl
As we have now nodes which aren't necessary in the preferred zone, we need to deploy these independent of the datacenter
=> Remove datacenters from system jobs

packages/orchestrator/internal/sandbox/nbd/dispatch.go
If the context is canceled, there no receiver for the channel which results forever blocking the goroutine
Snippet (there are much more) from an orchestrator goroutines
```
Goroutine 3027010832 - User: /build/orchestrator/internal/sandbox/nbd/dispatch
.go:265 github.com/e2b-dev/infra/packages/orchestrator/internal/sandbox/nbd.(*Di
spatch).cmdWrite.func1.1 (0x15a9e18) [chan send 858079709754578]
Goroutine 3027010834 - User: /build/orchestrator/internal/sandbox/nbd/dispatch
.go:265 github.com/e2b-dev/infra/packages/orchestrator/internal/sandbox/nbd.(*Di
spatch).cmdWrite.func1.1 (0x15a9e18) [chan send 858079709754578]
Goroutine 3027010835 - User: /build/orchestrator/internal/sandbox/nbd/dispatch
.go:265 github.com/e2b-dev/infra/packages/orchestrator/internal/sandbox/nbd.(*Di …
```
=> Fix goroutine leak in nbd

packages/envd/main.go
- allowed some headers in we're now sending from client in CORS (required for newer SDKs to pass browser tests)
=> envd: allow SDK headers in CORS

packages/orchestrator/internal/template/build/configure.sh
Handle gracefully already existing user `user` when configuring a sandbox template. This fixes the following Dockerfile build below. This PR also improves logging of the adduser log output.
```
FROM ubuntu:latest
RUN useradd -m user && \
chown -R user:user /home/user
```
=> Handle gracefully already existing user

packages/api/internal/template-manager/template_manager.go
Increase template waiting state deadline to 40 minutes (from 20 minutes) to allow larger (and slower) Docker image builds.
=> Increase template waiting state deadline

packages/shared/pkg/logger/exporter.go, packages/shared/pkg/logger/sandbox/logger.go
This PR removed the `BufferedWriteSyncer` and replaces it with simple `HTTPExporter` directly.
**Bug description**
Previous implementation using `BufferedWriteSyncer` caused the logging to be blocked. This is because `BufferedWriteSyncer` locks `write` when doing `flush`, and `flush` calls `Sync`, effectively awaiting all HTTPRequests synchronously on write.
Also, as we're sending log message one by one anyway, this buffering was causing delayed spam on the logs collector instead of sending messages gradually.
=> Fix blocking sandbox logger

packages/cluster/client/main.tf
This should allow rolling updates even for such case and prevent following error:
```
Resizing of autoscaled regional managed instance groups is not allowed. If you want to manually adjust target size remove the autoscaler or set autoscaling policy mode to OFF.
```
=> Turn off autoscale if autoscale not allowed

packages/api/internal/cache/instance/sync.go
Fixes a race condition, where the sandbox could be starting, but not yet returned from the orchestrator, causing immediate eviction and sandbox stop. This will result into 502 (sandbox not running/timeout) for the user.
All sandboxes that are started won't be synchronized from the orchestrator in a 10 second period. This is not optimal fix, but should be ok for now until we resolve the issue in general.
=> Fix nodes sync race condition

packages/orchestrator/internal/template/build/build.go, packages/orchestrator/internal/template/build/command.go, packages/orchestrator/internal/template/build/oci/oci.go, packages/orchestrator/internal/template/build/ready_command.go, packages/orchestrator/internal/template/build/rootfs.go, packages/orchestrator/internal/template/build/tar.go, packages/orchestrator/internal/template/build/template_builder.go, packages/shared/pkg/artifacts-registry/registry.go, packages/shared/pkg/artifacts-registry/registry_aws.go, packages/shared/pkg/artifacts-registry/registry_gcp.go, packages/shared/pkg/artifacts-registry/registry_local.go
Pass env vars from the Docker image to the start and ready commands. All ENV defined in the Docker image can now be referenced in the start and ready commands.
**Example Dockerfile**
`ENV E2B_TEST_VAR="Hello World E2B!"`
**Example e2b.toml**
`start_cmd = "echo $E2B_TEST_VAR"`
**Output**
`[start] [stdout]: Hello World E2B!`
=> Pass env vars from the Docker image to the start and ready commands

packages/api/main.go, packages/client-proxy/main.go, packages/orchestrator/cmd/build-template/main.go, packages/orchestrator/main.go, packages/shared/pkg/logger/logger.go, packages/shared/pkg/logger/sandbox/logger.go
Fix external sandbox logs from services. This fixes printing logs meant for sandboxes to the console from the API/Orchestrator.
=> Fix external sandbox logs from services

packages/api/internal/dns/server.go, packages/api/internal/handlers/store.go, packages/api/internal/orchestrator/orchestrator.go
We have our own `Rediser` abstraction on top of the client and cluster client implementations. We can use `redis.UniversalClient` that is delivered by redis library that we are using.
=> Replace our own abstraction on top of the redis client

packages/cluster-disk-image/main.pkr.hcl
Currently in newer GCP source images for ubuntu 2204 LTS we are experiencing problems with consul dns.
This is hot fix that will make it stable for source image re-builds.
=> Make cluster source image version fixed to specific release

packages/api/internal/template-manager/client.go, packages/nomad/api.hcl, packages/nomad/main.tf
Because of `http://` prefix the url parses to resolves `http://template-manager.service.consul:5008:443`
Also renamed the environment variable to prevent confusion.
```
2025-06-23T23:00:01.527Z  ERROR  failed to get health status of template manager  {"service": "orchestration-api", "internal": true, "pid": 1, "error": "failed to exit idle mode: invalid target address http://template-manager.service.consul:5008, error info: address http://template-manager.service.consul:5008:443: too many colons in address"}
github.com/e2b-dev/infra/packages/api/internal/template-manager.(*GRPCClient).healthCheckSync
/build/api/internal/template-manager/client.go:91
```
=> Fix template manager connection

packages/db/migrations/20250624001047_deploy_cluster_policy.sql
Enable row-level security for the clusters table. Needed because of the Supabase access model.
=> Added row lever security for cluster table

self-host.md
Added section on how to initiate quotas before deploying e2b - not sure if the guide should be this user friendly, but could save quite some time a less experienced GCP person :)
=> Update self-host.md to contain Google Cloud Quota troubleshoot guide

packages/api/internal/template-manager/template_manager.go
Removed duplicated lock, that never released because `tm.GetLocalClientStatus` already calls for status lock.
=> Fix local template manager deadlock

packages/api/internal/orchestrator/cache.go, packages/api/internal/orchestrator/client.go, packages/api/internal/orchestrator/metrics.go, packages/api/internal/orchestrator/node.go
If the API discovers the orchestrator before the orchestrator is healthy, it will add it with version, commit and orchestratorID equal to `unknown` and it won't be updated.
=> Update metadata during sync

packages/shared/pkg/storage/storage_aws.go
`io.ReadFull` will in that case return `ioErrUnexpectedEOF`, but service is expecting to receive `io.EOF` to know we that file download is complited.
=> Handle Unexpected EOF for ReadAt in AWS S3 storage provider

packages/nomad/api.hcl, packages/nomad/edge.hcl, packages/nomad/main.tf
Fix Redis client usage in cluster mode. This is a fix for regression introduced in: https://github.com/e2b-dev/infra/pull/769
The issue is that now the REDIS_URL will initialize just regular Redis client even when cluster one should be user. Redis requests than can error out with ERROR MOVED messages.
=> Fix Redis in cluster mode

packages/api/internal/edge/pool.go
Goroutine with sync start was executed before we initialized the struct that was run in that goroutine so this was leading to a race condition if goroutine creation was fast enough.
=> Fix edge pool race condition

packages/api/internal/auth/middleware.go
Previous link was going to 404, replaced with a current one.
=> Updated auth middleware error message link

packages/orchestrator/internal/proxy/proxy.go, packages/shared/pkg/proxy/host.go, packages/shared/pkg/proxy/host_test.go
After this change, we can stop sending the client part during sending traffic to the sandbox.
=> Traffic proxy working without client part

packages/api/internal/orchestrator/list_instances.go
This must be released in next batch after relese of https://github.com/e2b-dev/infra/pull/872. Ideally we need to wait 24 hours, at this time all new and running sandboxes will already use client ID constant so its safe to assume all sandboxes from orchestrators should be propagated to users with static client part.
=> Use static client id for sandboxes sync after api restart

packages/api/internal/cache/templates/cache.go, packages/api/internal/handlers/sandbox_create.go
Currently, when I am running a cluster for my team and I want to spawn a public template, it will try and fail until the timeout for spawning is hit. This is because the base template is not built on a remote cluster, but because it's public, it's assumed it's there.
We want to add a check into the template cache that will also compare clusters, so we can return some user-friendly error message.
=> Restrict template cache with cluster ID

packages/orchestrator/internal/sandbox/fc/process.go, packages/orchestrator/internal/sandbox/sandbox.go, packages/orchestrator/internal/server/sandboxes.go
- Add logs to check when the FC process gets into the `D` state
- Await for the FC process exit before stopping the uffd memory handler and continuing with the rest of the cleanup
- This might have been the primary cause of the stuck syscalls
- Move the stop/cleanup in `Delete` method to a goroutine
- This PR also add to the https://github.com/e2b-dev/infra/pull/896 that ensures the cleanup is not cancelled because of the context
=> Fix race condition in the FC process shutdown and cleanup

self-host.md
The self-host.md was outdated, since the Dashboard has no Developer Settings anymore.
=> Docs: Remove dashboard domain setting instructions from self-host documentation

packages/clickhouse/migrations/20250721084412_routing.sql
Drop old OTEL created metrics table and use them only for routing purposes
=> Clickhouse - Use otel table only for routing

packages/api/internal/orchestrator/cache.go, packages/api/internal/orchestrator/client.go, packages/api/internal/orchestrator/create_instance.go, packages/api/internal/orchestrator/delete_instance.go, packages/api/internal/orchestrator/node.go, packages/api/internal/orchestrator/orchestrator.go, packages/api/internal/orchestrator/pause_instance.go, packages/client-proxy/internal/edge-pass-through/events.go, packages/client-proxy/internal/edge-pass-through/proxy.go, packages/client-proxy/main.go, packages/shared/pkg/edge/events.go
Remove the need to call the Edge REST API for sandbox registry/remove from cluster shared cache.
This PR introduces changes that will move sandbox catalog create/delete requests directly into sandbox start/delete/pause metadata. It should simplify the process of calling and speed up startup, because it's no longer another request.
=> Send edge sandbox catalog as gRPC metadata

packages/envd/internal/services/filesystem/dir.go, packages/envd/internal/services/filesystem/move.go, packages/envd/internal/services/filesystem/stat.go, packages/envd/internal/services/filesystem/stat_test.go, packages/envd/internal/services/filesystem/utils.go, packages/envd/internal/services/filesystem/utils_test.go, packages/envd/main.go
os.Stat gives information about resolved symlinks, that caused issues with `symlinkTarget` for `Stat` method.
Refactor the entryInfo method to prevent such bugs
=> Fix envd symlink resolution

Makefile, main.tf, packages/nomad/main.tf, packages/nomad/orchestrator.hcl, packages/nomad/variables.tf, variables.tf
This timeout is used when waiting for the sandbox to become healthy. Before this point, there are parts of the process where things should fail quickly. At this point, however, we're waiting for customer-provided code to become healthy, and we don't control this duration. Let's give them as much time as we can, while still providing some room for a retry if it takes too long. The client SDK defaults to a 60 second timeout, so 40 seconds gives them enough time to try twice, although the second attempt won't have as long as the first to complete successfully.
=> Increase envd timeout

packages/envd/internal/services/process/handler/handler.go, packages/envd/main.go, tests/integration/internal/tests/envd/process_test.go, tests/integration/internal/utils/process.go
Ensure the working directory exists before executing any command. Running commands in a non-existent directory can cause unpredictable behavior, including silent failures, incorrect error messages, or commands executing in unexpected locations (such as the parent directory or system root).
This solution fails immediately when the directory doesn't exist to communicate the reason to the user. This a difference from how Dockerfile behaves, but keeps the behavior clear as it's a bit unexpected situation.
=> Ensure workdir exists before running a command

packages/envd/go.mod, packages/envd/go.sum, packages/envd/main.go
This pull request includes a couple of small changes in fsnotify, namely:
- Skip the folder in recursive mode if the user doesn't have permissions
e2b-dev/fsnotify#3
- inotify: fix race when adding/removing watches while a watched path is being
deleted fsnotify/fsnotify#678, fsnotify/fsnotify#686
- inotify: don't send empty event if a watched path is unmounted fsnotify/fsnotify#655
- inotify: don't register duplicate watches when watching both a symlink and its
target; previously that would get "half-added" and removing the second would
panic fsnotify/fsnotify#679
=> Update fsnotify 

packages/api/main.go
This pull request includes a small change to the `NewGinServer` function in `packages/api/main.go`. The change adds support for the `User-Agent` header in the list of allowed headers.
=> Add user agent header

packages/api/internal/handlers/sandbox_metrics.go, packages/api/internal/handlers/sandboxes_list_metrics.go
Cut out the second part from sandbox id if passed
=> Make metrics long sandbox ID compatible

packages/orchestrator/internal/template/build/command/user.go
Fix build user creation with no password and also exit with 0 when the user already exists
=> Fix build user creation

packages/api/internal/handlers/sandboxes_list.go, packages/db/queries/get_snapshots_with_cursor.sql, packages/db/queries/get_snapshots_with_cursor.sql.go, tests/integration/internal/tests/api/sandbox_list_test.go
The problem is that we created the cursor from `StartedAt`, but the query was using `CreatedAt` at DB, causing a potential race condition.
=> Fix pagination query

packages/api/internal/orchestrator/cache.go, packages/api/internal/orchestrator/client.go, packages/api/internal/orchestrator/create_instance.go, packages/api/internal/orchestrator/node.go
Context: For clusters, we are adding the service instance ID to requests used in the edge proxy to determine which orchestrator/template builder should route the request. This ID changes when the orchestrator is restarted.
In production environments, we are not supporting orchestrator restarts. It should never happen to have the same node ID and changed service instance ID, but when developing, restarts are allowed. This was causing the API to be unable to communicate with the orchestrator, because the service instance ID was outdated, as it was issued only during cluster node connection and was never updated.
=> Always use actual service instance ID during gRPC call 

Makefile
Enhancements to Terraform state bucket management:
* Enabled object versioning and soft delete for the Terraform state bucket to retain deleted or replaced objects for 30 days.
* Added lifecycle rules to automatically delete non-live objects older than 30 days and to remove objects if there are more than 50 newer versions, using a temporary lifecycle configuration file during initialization.
=> Add versioning and lifecycle rules to the terraform state bucket

packages/api/internal/handlers/template_request_build.go
Improve template permission and not found errors.
Before:
404: Error when getting template `templateID` for team `teamID`
After:
404: Template `templateAlias (if provided, otherwise templateID)` not found
403: Template `templateAlias (if provided, otherwise templateID)` is not accessible for the team `teamID`
Note:
This change makes it more transparent to foreign teams to see if a template alias already exists (because they can now distinguish between not access and template not existing).
=> Improve template permission and not found errors

packages/orchestrator/Dockerfile
As of August 14:
golang:1.24 (latest):
- Based on Debian 13 "Trixie" (new stable)
- Has glibc 2.41 (very new)
- Created: August 12, 2025
golang:1.24-bullseye:
- Based on Debian 11 "Bullseye" (old-old stable, released 2021)
- Has glibc 2.31 (older, stable)
- Compatible with your server's glibc 2.35
The build with new glibc will fail to run client nodes due mismatched glibc versions: local/orchestrator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by local/orchestrator)
=> Update Dockerfile - force use golang:1.24-bullseye

packages/api/internal/cache/instance/lifecycle_cache_test.go
Before:
```
=== RUN   TestLifecycleCacheHasEvicting
==================
WARNING: DATA RACE
Read at 0x00c0001a2ecf by goroutine 495:
github.com/e2b-dev/infra/packages/api/internal/cache/instance.(*testLifecycleCacheItem).IsExpired()
/Users/djeebus/code/e2b/infra/packages/api/internal/cache/instance/lifecycle_cache_test.go:19 +0x40
github.com/e2b-dev/infra/packages/api/internal/cache/instance.(*lifecycleCache[go.shape.*uint8]).Start()
/Users/djeebus/code/e2b/infra/packages/api/internal/cache/instance/lifecycle_cache.go:59 +0x1e0
github.com/e2b-dev/infra/packages/api/internal/cache/instance.newCache.gowrap1()
/Users/djeebus/code/e2b/infra/packages/api/internal/cache/instance/lifecycle_cache_test.go:30 +0x58
Previous write at 0x00c0001a2ecf by goroutine 494: …
```
=> Fix a race condition in a test

packages/db/migrations/20250820102103_add_snapshots_indexes.sql
Add indexes to improve the query performance for paused sandboxes (`GetSnapshotsWithCursor`)
=> Fix paused sandboxes list query performance

.github/actions/build-packages/action.yml
`go.work.sum` is excluded from the repo since #869 , so the shortcut introduced in #1016 no longer works. This change looks up all go.mod/go.sum files without requiring full recursion.
=> Fix the cache key

packages/orchestrator/internal/sandbox/template/storage_template.go, packages/orchestrator/internal/template/build/storage/cache/cache.go, packages/orchestrator/internal/template/metadata/template_metadata.go, packages/orchestrator/internal/template/metadata/template_metadata_test.go
Deprecate all v1 metadata versions. This fixes new templates with v1 metadata (invalid version type).
=> Deprecate all v1 metadata versions

packages/api/internal/edge/cluster_instances.go
Fix for a development environment where the orchestrator can restart on the same node and get a new instance ID.
When the instance ID changes (even if the node ID is still the same), we want to properly trigger pool removal.
=> Make sure we are comparing service id, not just node id

main.tf, packages/nomad/main.tf, packages/nomad/variables.tf, packages/orchestrator/internal/sandbox/network/firewall.go, packages/orchestrator/internal/sandbox/sandbox.go
Needed for K8s support, where you can set env with host/pod ip, but you cannot adjust it with, for example, `http://` prefix.
=> Make sure logs collector ip is named properly and its always just IPv4

packages/shared/pkg/storage/storage_aws.go, packages/shared/pkg/storage/storage_cache.go, packages/shared/pkg/storage/storage_google.go
- This should also correctly propagate the error in `WriteTo` in the cached provider.
=> Propagate `ErrorObjectNotExist` from AWS and GCP storage providers when calling `.Size()`

packages/api/internal/orchestrator/client.go, packages/api/internal/orchestrator/nodemanager/node.go
After node refactoring, the cluster node is not getting the gRPC metadata needed for proper request handling.
The initial call will fail as metadata is not present.
=> Missing request metadata during node registration

packages/orchestrator/internal/sandbox/template/cache.go, packages/orchestrator/internal/server/sandboxes.go, packages/orchestrator/internal/template/build/layer/create_sandbox.go, packages/orchestrator/internal/template/build/layer/interfaces.go, packages/orchestrator/internal/template/build/layer/layer_executor.go, packages/orchestrator/internal/template/build/layer/resume_sandbox.go, packages/shared/pkg/storage/storage_cache.go
This also cleans up logging and returns a struct rather than an interface in one place.
=> Do not cache when building a template, only when starting a sandbox

packages/api/internal/orchestrator/placement/placement.go, packages/api/internal/orchestrator/placement/placement_test.go, packages/orchestrator/internal/server/main.go, packages/orchestrator/internal/server/sandboxes.go, tests/integration/internal/tests/api/kill_test.go
Enforce max concurrent sandboxes per node in the orchestrator instead of API and increase retry limit
This is a next step for moving towards stateless API.
Starting 3 sandboxes concurrently on a node should be very improbable, so it's better to check during the placement instead of doing extra call to some centralized storage to get the number of concurrently starting sandboxes on the node.
=> Enforce max concurrent sandboxes per node in the orchestrator

packages/api/internal/edge/cluster.go, packages/api/internal/orchestrator/cache.go, packages/api/internal/orchestrator/nodemanager/metadata.go, packages/api/internal/orchestrator/nodemanager/node.go, packages/api/internal/orchestrator/nodemanager/sync.go, packages/shared/pkg/synchronization/synchronization.go
- (2b9091d9bb99d9cc6d8a0744b2688742bc705883) Fix issue when a long blocked run of `PoolExists/PoolUpdate` can cause a timeout for the whole sync run. This issue occurred when the orchestrator failed and the sync was blocked due to a timeout in the gRPC info service of one node, while the other node was simply hanging. 
- (c8540f72a74a1b14a078a12bb906dae089586301) Fixing race condition when orchestrator on same node restarter faster than next round of service discovery finishes, so api cluster sync pool never realized node disappeared and node de-registration was never triggered, leaving existing node with matching node id but outdated service instance id.
=> Nodes sync race condition

packages/orchestrator/internal/template/build/sandboxtools/command.go
Increase hard command timeout for template building. Fixes max layer build timeout that was fixed to 10 minutes, but it should have been 1 hour. The command timeout should be handled by the context cancellation otherwise.
=> Increase hard command timeout for template building

packages/envd/internal/services/filesystem/watch_sync.go, tests/integration/internal/tests/envd/watcher_test.go
- This pull request fixes an issue where watcher was closed right after the request for create was completed (introduced in [#981](https://github.com/e2b-dev/infra/pull/981/files#diff-834039e24b75798bfaf83a9fc463fdb0f5d07445d59ea3d823957da0f8dc3c30))
- Added a integration test (fails without the patch)
=> Fix regression for envd watcher

packages/nomad/template-manager.hcl
Add multiple template managers in the Nomad job. This is achieved by changing the job type from `service` to `system`. Unfortunately, service doesn't support the update strategy we need (first stop the current job, then run the new one, one by one across nodes).
=> Add multiple template managers in Nomad job

Makefile, main.tf, packages/cluster/build-cluster/main.tf, packages/cluster/build-cluster/variables.tf, packages/cluster/client/main.tf, packages/cluster/client/variables.tf, packages/cluster/main.tf, packages/cluster/variables.tf, variables.tf
This exposes a few fields to customize the cpu and disk type for the build and client nodes, but keeps the defaults the same.
=> Support cpu platform and disk type configuration

packages/api/internal/orchestrator/evictor/evict.go
Don't try to evict, if the sandbox is already being removed (it was only printing unnecessary errors)
=> Skip evict if the sandbox is already being removed

packages/orchestrator/internal/metrics/sandboxes.go
Added envd version for easier debugging and query analytics
=> Report envd version for clock drift warns

iac/provider-gcp/nomad/configs/otel-collector.yaml, iac/provider-gcp/nomad/jobs/otel-collector.hcl, packages/otel-collector/Makefile
Changes are currently present in our [forked repository](https://github.com/e2b-dev/opentelemetry-collector-contrib/pull/1) until the official repository adapts it.
=> Run OTEL with hugepages metrics

.github/workflows/pull-request.yml
If we open a pull request to another pull request, we'd still like to know if it's going to break the build before merging. For example, [#1168](https://github.com/e2b-dev/infra/pull/1168) points at [#1167](https://github.com/e2b-dev/infra/pull/1167) as an option for resolving a comment. It's not clear that we want to go this way, so it makes sense to open it as a PR so we can talk about it. However, I'd like to know that it actually works before merging it.
=> Run pull request jobs on all pull requests

packages/api/internal/cache/templates/cache.go, packages/api/internal/template-manager/template_status.go
Remove template build spammy logs. There is no need to log the same info twice. Also, the template SDK requests the build status every 200ms, so the log message that returns the state from the cache is spammed extensively.
=> Remove template build spammy logs

packages/api/Dockerfile, packages/client-proxy/Dockerfile, packages/docker-reverse-proxy/Dockerfile
Fix Docker build with go 1.24.7. Version `alpine3.20` contains Golang 1.24.3.
=> Fix Docker build with go 1.24.7

packages/api/internal/dns/server.go
Remove noisy log -we have a corresponding message in client proxy anyway
=> Remove noisy log from API

packages/envd/internal/api/init.go, packages/envd/internal/api/store.go, packages/envd/main.go
Fixes the issue causing concurrent writing to the hosts file, as it sometimes occurs when we call init multiple times.
=> Fix concurrent hosts file write during sbx start
