e2b-dev/infra

Makefile, scripts/confirm.sh
To prevent accidentaly affecting production when you think you are in staging env.
=> Add confirmation before manual deployment to production

packages/docker-reverse-proxy/internal/auth/validate.go, packages/docker-reverse-proxy/internal/handlers/login.go, packages/docker-reverse-proxy/internal/handlers/proxy.go, packages/docker-reverse-proxy/internal/handlers/token.go, packages/docker-reverse-proxy/main.go
There was a problem when trying to login to docker repository from Windows.
There was an extra whitespace coming inside the auth token.
=> Fix docker login for Windows

packages/api/internal/handlers/template_request_build.go
When specifying new alias, remove the old ones
=> Remove old alias

packages/cluster/scripts/start-client.sh
Allocate huge pages after mounting buckets to lower the time to sandbox after the client starts. Also lower the preallocated huge pages in favor of overcommited huge pages.
=> Improve huge pages handling in client start script

packages/cluster-disk-image/main.pkr.hcl, packages/nomad/api.hcl, packages/nomad/client-proxy.hcl, packages/nomad/docker-reverse-proxy.hcl, packages/nomad/logs-collector.hcl, packages/nomad/loki.hcl, packages/nomad/orchestrator.hcl, packages/nomad/otel-collector.hcl, packages/nomad/session-proxy.hcl
Improve the priority and resources of Nomad jobs, remove unused meta fields, and change session proxy to system job.
=> Update and simplify Nomad jobs

packages/cluster/scripts/run-consul.sh, packages/cluster/scripts/start-client.sh
Add default consul agent token to deregister jobs and update node
=> Add default consul agent token

packages/cluster/main.tf, packages/cluster/server/main.tf, packages/cluster/server/variables.tf
Allow only for max 1 server to be unavailable
=> Decrease max unavailable servers to 1

packages/nomad/client-proxy.hcl, packages/nomad/otel-collector.hcl, packages/nomad/session-proxy.hcl
Export logs and metrics from session and client proxy
=> Add logs and metrics from proxies

packages/api/internal/auth/middleware.go, packages/api/internal/cache/auth/cache.go, packages/api/internal/cache/templates/cache.go, packages/api/internal/handlers/sandbox_create.go, packages/api/internal/handlers/sandbox_kill.go, packages/api/internal/handlers/sandbox_logs.go, packages/api/internal/handlers/sandboxes_list.go, packages/api/internal/handlers/store.go, packages/api/internal/handlers/template_delete.go, packages/api/internal/handlers/template_start_build.go, packages/api/main.go, packages/orchestrator/internal/sandbox/fc.go, packages/shared/pkg/db/apiKeys.go, packages/shared/pkg/db/users.go
Cache DB requests to improve sandbox start speed
=> Optimize db access

packages/template-manager/internal/build/rootfs.go
=> chore: update rootfs.go

packages/cluster-disk-image/main.pkr.hcl, packages/cluster-disk-image/setup/limits.conf
When there's a lot of traffic we are hitting limits for open connections, also the number of open files may not be sufficient, increasing it should help
=> Increase limit for number of open files and connections

packages/api/internal/cache/builds/build_cache.go, packages/api/internal/cache/instance/instance.go, packages/api/internal/cache/instance/monitoring.go, packages/api/internal/cache/instance/operations.go, packages/api/internal/cache/instance/sync.go, packages/api/internal/handlers/sandbox_create.go, packages/api/internal/handlers/store.go, packages/api/internal/meters/main.go, packages/nomad/otel-collector.hcl, packages/shared/pkg/telemetry/otel.go
- Add counter for creating sandbox to get the rate how many new sandboxes are created per some interval
- Add counter for number of sandboxes being currently rate limited
- Decrease reporting interval to 30s
=> Improved monitoring

packages/api/internal/cache/builds/build_cache.go, packages/api/internal/cache/instance/instance.go, packages/api/internal/handlers/sandbox_create.go, packages/nomad/otel-collector.hcl, packages/orchestrator/internal/sandbox/cache/mmapfile.go, packages/orchestrator/internal/sandbox/checks.go, packages/orchestrator/internal/sandbox/fc.go, packages/orchestrator/internal/sandbox/mock_instance.go, packages/orchestrator/internal/sandbox/network.go, packages/orchestrator/internal/sandbox/pool.go, packages/orchestrator/internal/sandbox/sandbox.go, packages/orchestrator/internal/sandbox/slot.go, packages/orchestrator/internal/sandbox/stats.go, packages/orchestrator/internal/server/main.go, packages/orchestrator/internal/server/sandboxes.go, packages/orchestrator/main.go, packages/shared/pkg/meters/main.go, packages/shared/pkg/telemetry/otel.go
- We can reuse network slot without releasing it
- Add counters to monitor how many network slots are in the pool
=> Reuse networks

.env.template, README.md, self-host.md
Went through the self-hosting guide and added more notes and explained some nuances
<details open>
Updated the self-hosting guide with additional notes and explanations for better clarity.
<details>
```mermaid
actor User
participant GCP
participant Cloudflare
participant Supabase
participant Atlas
User->>GCP: 1. Create new project
User->>GCP: 2. Login via gcloud
User->>Cloudflare: 3. Get API Token
User->>Supabase: 4. Get Postgres connection string
User->>GCP: 5. Create storage bucket for Terraform state
User->>Atlas: 8. Login to Atlas CLI
User->>Supabase: 9-10. Setup & run DB migrations
User->>GCP: 11. Initialize Terraform (enable APIs)
User->>GCP: …
```
=> Update self-hosting guide

packages/api/internal/handlers/sandbox_get.go
- Drops -clientId when querying sandbox-clientId
=> Ignore client id when retrieving a sandbox

self-host.md
Add a section on how to use the cluster after it's set up.
=> Update self host document

packages/nomad/main.tf, packages/nomad/orchestrator.hcl
This should make development faster and easier
=> Add condition to instant replace the orchestrator on staging

packages/api/main.go
@jakubno spotted a bug where the program was returning too early. We
weren't waiting on the HTTP service to return. This should resolve
that defect.
I think slightly longer term I'd like to have less bespoke shutdown
code, but this should take care of things.
=> api: block shutdown till http service returns

packages/api/internal/dns/server.go, packages/api/internal/handlers/store.go, packages/api/internal/orchestrator/orchestrator.go
create the redis client and connect it to the DNS service.
required for and connected to #261
=> api: create and initialize redis client

packages/api/internal/handlers/sandbox_kill.go, packages/api/internal/handlers/template_delete.go, packages/shared/migrations/20250206105106.sql, packages/shared/pkg/db/envs.go, packages/shared/pkg/db/snapshot.go
Removes paused sandboxes from the DB
=> Kill paused sandboxes

.env.template, Makefile, main.tf, packages/cluster/client/main.tf, packages/cluster/client/variables.tf, packages/cluster/main.tf, packages/cluster/variables.tf, variables.tf
The scaling down is turned off for obvious reasons.
=> Add autoscaling (only up) for client

packages/api/internal/handlers/sandboxes_list.go, packages/api/internal/handlers/sandboxes_list_metrics.go
To avoid conflicts with my open PR
=> Moved sandbox metrics endpoint to a separate file

packages/client-proxy/main.go
- Add logging 
- Log all access and response status code
- Log errors
- Set similar timeouts as we had in nginx
=> Client proxy improvements

.github/workflows/periodic-test.yml, .gitignore, tests/periodic-test/build-template/e2b.Dockerfile, tests/periodic-test/build-template/index.ts, tests/periodic-test/create-file.ts, tests/periodic-test/run-code.ts, tests/periodic-test/snapshot-and-resume.ts
We want to be able to run periodic liveness tests for our infrastructure across multiple clusters. 
This pr introduces some tests and patterns to accomplish this
=> Run periodic tests in github actions to determine liveness

Makefile, main.tf, packages/cluster/main.tf, packages/cluster/network/main.tf, packages/cluster/network/variables.tf, packages/cluster/variables.tf, variables.tf
This allows us to have multiple domains on the same cluster
=> Add support for multiple domains on the same cluster

packages/api/internal/handlers/sandbox.go, packages/api/internal/handlers/store.go, packages/shared/pkg/meters/main.go
Remove sandbox create rate limiting
=> Remove sandbox create rate limiting

packages/orchestrator/internal/sandbox/fc/process.go
Try to change how sandbox kill work to prevent accumulation of FC processes.
=> Rework sandbox kill

packages/api/internal/handlers/sandbox_refresh.go, packages/api/internal/handlers/sandbox_timeout.go, packages/api/internal/orchestrator/keep_alive.go, packages/api/internal/orchestrator/update_instance.go
Send info about changed TTL to orch, so it can be synced if we roll API
=> Propagate new stopped at for sandbox to orchestrator

main.tf, terraform/grafana/README.md, terraform/grafana/main.tf
create connection from gcp logs to grafana using terraform
=> Provision gcp logs data source for grafana with terraform

Makefile
add make commands for grafana in root makefile for more convenient devex
=> add make commands for grafana in root makefile

.github/workflows/heath-check.yml, .github/workflows/periodic-test.yml, .github/workflows/release.yml
This PR:
- disables the unused release workflow
- disables the outdated periodic healthcheck
- stops the new periodic check trigger on non-main branches
In the next PR:
=> Cleanup GitHub Actions

packages/api/internal/orchestrator/create_instance.go
Improve sandbox create retry log, exit on context done. Better message for the http response.
=> Improve sandbox create retry log, exit on context done

packages/orchestrator/internal/sandbox/fc/process.go, packages/orchestrator/internal/sandbox/sandbox.go
=> Fix leaks in orchestator

packages/api/Dockerfile, packages/api/Makefile, packages/api/main.go, packages/client-proxy/Dockerfile, packages/client-proxy/Makefile, packages/client-proxy/main.go, packages/docker-reverse-proxy/Dockerfile, packages/docker-reverse-proxy/Makefile, packages/docker-reverse-proxy/main.go, packages/orchestrator/Dockerfile, packages/orchestrator/Makefile, packages/orchestrator/main.go, packages/template-manager/Makefile, packages/template-manager/main.go
Add initial log with commit hash
=> Add initial commit logs

.env.template, Makefile, main.tf, packages/cluster/build-cluster/main.tf, packages/cluster/build-cluster/outputs.tf, packages/cluster/build-cluster/variables.tf, packages/cluster/main.tf, packages/cluster/network/main.tf, packages/cluster/network/variables.tf, packages/cluster/scripts/run-build-cluster-nomad.sh, packages/cluster/scripts/run-nomad.sh, packages/cluster/scripts/start-build-cluster.sh, packages/cluster/variables.tf, packages/nomad/docker-reverse-proxy.hcl, packages/nomad/template-manager.hcl, variables.tf
Create a new node pool for template manager and docker reverse proxy, so it doesn't interfere with sandbox orchestration
=> Move template manager to separate node

DEV.md
=> Remove outdated info in Dev.md

packages/api/internal/handlers/sandbox.go, packages/api/internal/handlers/sandbox_create.go, packages/api/internal/handlers/sandbox_resume.go, packages/api/internal/orchestrator/create_instance.go
- Reenable rate limiting based on tier
- Return correct status codes
=> Reenable rate limiting

packages/api/internal/cache/instance/instance.go, packages/api/internal/cache/instance/operations.go, packages/api/internal/handlers/sandbox_resume.go, packages/api/internal/orchestrator/cache.go, packages/api/internal/orchestrator/delete_instance.go
Add debug logs to understand more pause/sync issue (periodic checks fails)
=> Add debug logs to understand more pause/sync issue

.github/workflows/periodic-test.yml, tests/periodic-test/cli-logs.ts
test that our logging infrastructure is operational
=> Test logging from e2b cli is operating normally

packages/api/internal/handlers/sandbox_logs.go, packages/api/internal/handlers/sandbox_metrics.go, packages/nomad/logs-collector.hcl
- Change filtering only based on sandbox id, team id and exclude metrics
- Remove labels from logs
- Allow out of order logs
=> Not all logs sandbox lifecycle are present

.github/actions/start-services/action.yml
Error out when orchestrator or api fails during start
=> Improve integration tests error when orchestrator or api fails during start

packages/cluster/api-cluster/main.tf, packages/cluster/build-cluster/main.tf, packages/cluster/client/main.tf
=> Fix opportunistic typo

packages/nomad/orchestrator.hcl
Fix terraform dev environment (replace staging to dev)
=> Fix terraform dev environment

packages/shared/pkg/db/envs.go
It's basically the same as the original query would do, but now we have better observability and we are doing exact match instead of `IN`, which would ORM use
=> DB Improvements - Split query

tests/periodic-test/build-template/index.ts, tests/periodic-test/cli-logs.ts, tests/periodic-test/create-file.ts, tests/periodic-test/internet-works.ts, tests/periodic-test/run-code.ts, tests/periodic-test/snapshot-and-resume.ts, tests/periodic-test/utils.ts
Add timestamp to improve debugging
=> Add timestamp to periodic checks

.github/workflows/integration_tests.yml, .github/workflows/pr-go-integrity.yml, .github/workflows/pr-tests.yml
- will cancel in-progress CI runs when newer commits have been added to the PR
=> Cancel CI builds for same PR in progress

packages/cluster/security/vpc-flow.sh
Because we are using default network it ain't really possible to use terraform without some imports. (We should use separate non-default network).
=> Add script to enable VPC flow

packages/template-manager/internal/build/snapshot_linux.go
Enable usage of IPv6 inside of sandboxes for internal use. This is to allow running e.g. [Supabase](https://supabase.com/docs/guides/self-hosting/docker), which is ipv6 only, inside of the sandbox using Docker. 
Changes the kernel parameters from:
`ipv6.disable=1`
to:
`ipv6.disable=0 ipv6.autoconf=1`
=> Enable IPv6 inside of sandboxes

main.tf, packages/cluster/main.tf, packages/cluster/security/main.tf, packages/cluster/security/variables.tf, packages/cluster/variables.tf, packages/init/main.tf, packages/init/outputs.tf
Adds alerting for IDS threats, if the IDS threat detection is already set up
=> Intrusion detection system alerts

packages/cluster/network/main.tf, packages/nomad/main.tf
Add firewall rule to allow traffic to logs collector
=> Allow sending data to logs collector

self-host.md
improves self hosts steps description and order. The e2b-postgres-connection-string is created only after the first plan-without-jobs apply.
=> Improve self-host steps

packages/cluster/network/main.tf
When I run `make plan` this file gets formatted. Lets commit this so its not polluting my prs :)
=> Commit formatted file to main

packages/fc-kernels/build.sh
Use amazon linux repo
- We can use FUSE again
=> New kernel build script

packages/api/Dockerfile
There were some changes in the package which resulted in broken build
=> Fix path in dockerfile

.github/actions/deploy-setup-staging/action.yml, .github/workflows/deploy-staging-infra.yml, .github/workflows/deploy-staging-jobs.yml
Fixes actions format and adds a requirement for a commit sha, tracking id
=> Fix staging deploy workflows

.github/actions/deploy-setup/action.yml, .github/workflows/build-and-upload-job.yml, .github/workflows/deploy-infra.yml, .github/workflows/deploy-job.yml, Makefile
This PR fixes bugs in deployment workflows after testing
=> Fix deployment workflows

packages/api/internal/handlers/sandboxes_list.go, packages/api/internal/handlers/sandboxes_list_metrics.go, packages/api/internal/utils/sandboxes_list.go
Refactor to simplify the logic
- split the function so the required parameter are really required
-  return better errors to user
=> Sandbox list PR Refactor

packages/client-proxy/main.go, packages/orchestrator/internal/proxy/proxy.go, spec/openapi.yml, tests/integration/internal/setup/envd_client.go
Our customer facing domain for cluster is currently e2b.app. Updates typos in codebase to make it clear everywhere.
=> Sync codebase with primary domain where cluster is running

packages/cluster-disk-image/.terraform.lock.hcl, packages/cluster-disk-image/Makefile, packages/cluster-disk-image/main.pkr.hcl, packages/cluster-disk-image/main.tf, packages/cluster-disk-image/variables.pkr.hcl, packages/cluster-disk-image/variables.tf
As we don't allow SSH connection by default, this change uses IAP to use google internal network
=> Fix connection issue for packer build

main.tf, packages/init/main.tf
- Fixes missing prefix
- Change name of the secret to security email to better match its intention
=> Terraform fix and improve naming

packages/nomad/otel-collector.hcl
This PR fixes the rpc.server.duration filtering invalid configuration
=> Fix rpc server duration filtering

packages/orchestrator/internal/sandbox/sandbox_linux.go, packages/shared/pkg/storage/header/diff.go, packages/template-manager/internal/build/build.go
Adds trace to CreateDiff, so we can better debug the speed of the transformation
=> Add create diff with trace

packages/shared/scripts/seed/postgres/seed-db.go
Fixes invalid column name after refactor
=> Fix db seed column name

terraform/grafana/stack/panels/api-nodes-cpu-utilization.json, terraform/grafana/stack/panels/api-nodes-network-throughput.json, terraform/grafana/stack/panels/api-nodes-ram.json, terraform/grafana/stack/panels/orchestrator-nodes-cpu-utilization.json, terraform/grafana/stack/panels/orchestrator-nodes-disk-cache-throughput.json, terraform/grafana/stack/panels/orchestrator-nodes-network-throughput.json
Fix missing prefix
Unify regex style
=> Fix missing prefix + unify regexes

packages/envd/internal/services/filesystem/dir.go, packages/envd/internal/services/filesystem/move.go, packages/envd/internal/services/filesystem/stat.go, packages/envd/internal/services/filesystem/utils.go, tests/integration/internal/tests/envd/filesystem_test.go
- Fixes file path when using list dir with depth
- Fixes integration test for listing dir
=> Fix integration tests

tests/integration/internal/tests/api/kill_test.go, tests/integration/internal/tests/api/sandbox_list_test.go, tests/integration/internal/tests/envd/auth_test.go
Avoids panic when there's error during pausing a sandbox
=> Avoid panic in list test

tests/periodic-test/cli-logs.ts, tests/periodic-test/create-file.ts, tests/periodic-test/internet-works.ts, tests/periodic-test/run-code.ts, tests/periodic-test/snapshot-and-resume.ts, tests/periodic-test/time-is-synchronized/index.ts
Add sandbox ID info missing in some periodic tests
=> Add sandbox ID info to periodic test

packages/orchestrator/internal/sandbox/nbd/dispatch.go, packages/orchestrator/internal/sandbox/nbd/path_direct_linux.go, packages/orchestrator/internal/sandbox/nbd/pool.go, packages/orchestrator/internal/sandbox/rootfs/cow.go, packages/orchestrator/internal/sandbox/sandbox_linux.go
We are experiencing a kernel NULL dereference that might be caused by incorrect NBD handling.
=> Improve NBD handling

tests/periodic-test/time-is-synchronized/index.ts
Read from the stdout and stderr by concurrently. Use also Deno stdout/stderr instead of console.log. Remove unnecessary newline on each line in the logs.
=> Improve periodic tests command output streaming

tests/periodic-test/time-is-synchronized/index.ts
Improve periodic tests error catch to show the underlying error source
=> Improve periodic tests error catch

tests/periodic-test/time-is-synchronized/index.ts
Rethrow periodic test error to cause test failure
=> Rethrow periodic test error

packages/template-manager/internal/build/snapshot_linux.go
Increase start command wait time for template building
=> Increase start command wait time

packages/nomad/logs-collector.hcl, packages/template-manager/cmd/build-template/main.go, packages/template-manager/internal/build/build.go, packages/template-manager/internal/build/network_linux.go, packages/template-manager/internal/build/network_other.go, packages/template-manager/internal/build/provision.sh, packages/template-manager/internal/build/rootfs.go, packages/template-manager/internal/build/snapshot_linux.go, packages/template-manager/internal/build/template.go, packages/template-manager/internal/build/writer/postprocessor.go, packages/template-manager/internal/build/writer/postprocessor_test.go, packages/template-manager/internal/test/build.go
Improve exposed logs to the user when building a new template to improve transparency and debugging issues.
This PR fixes also Vector timestamp parsing format of %f vs %.f (https://docs.rs/chrono/latest/chrono/format/strftime/index.html#fn5):
Example: 7μs is formatted as 7000 with %f, and formatted as .000007 with %.f.
<details>
<summary>Example of the new logs:</summary>
```
[2025-04-30T13:48:41Z] Starting postprocessing
[2025-04-30T13:48:41Z] Pulling Docker image...
[2025-04-30T13:48:46Z] ...
[2025-04-30T13:48:51Z] ...
[2025-04-30T13:48:56Z] ...
[2025-04-30T13:49:01Z] ...
[2025-04-30T13:49:06Z] ...
[2025-04-30T13:49:11Z] ...
[2025-04-30T13:49:16Z] ...
[2025-04-30T13:49:21Z] ...
[2025-04-30T13:49:26Z] ...
[2025-04-30T13:49:31Z] ...
[2025-04-30T13:49:36Z] ...
[2025-04-30T13:49:41Z] ... …
```
=> Improve template manager logs

packages/orchestrator/main.go
Initialize template manager only when enabled in orchestrator services
Fixes for the orchestrator job start:
```
2025/05/06 15:09:27 Validation for environment variables failed: missing environment variables: GCP_PROJECT_ID, GCP_DOCKER_REPOSITORY_NAME, GOOGLE_SERVICE_ACCOUNT_BASE64, GCP_REGION
```
=> Initialize template manager only when enabled in services

packages/orchestrator/main.go
If either proxy or grpc server fail, shutdown
=> Return early on a service error

packages/envd/main.go, packages/shared/pkg/proxy/proxy.go
=> Improve comments for idle timeouts

packages/cluster/network/main.tf
Enable logs for ingress firewall
=> Enable firewall logs for ingress

.github/workflows/periodic-test.yml
Disable staging periodic tests until Monday
=> Disable staging periodic tests

packages/orchestrator/internal/sandbox/build/cache.go
Because of bug in ttlcache RangeBackwards method, we need to handle potential panic until it gets fixed.
(example https://github.com/e2b-dev/infra/actions/runs/15070929902/job/42366869657)
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x714220]
goroutine 8 [running]:
container/list.(*Element).Prev(0xc00018c200?)
/opt/hostedtoolcache/go/1.23.7/x64/src/container/list/list.go:40
github.com/jellydator/ttlcache/v3.(*Cache[...]).RangeBackwards(0x152d480, 0xc000026e48)
/home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.3.1-0.20250207140243-aefc35918359/cache.go:582 +0xb4
github.com/e2b-dev/infra/packages/orchestrator/internal/sandbox/build.(*DiffStore).deleteOldestFromCache(0xc000[41](https://git …
```
=> Mitigate panic in ttlcache RangeBackwards

.github/workflows/periodic-test.yml
=> Reenable staging tests

packages/orchestrator/internal/grpcserver/server.go, packages/orchestrator/main.go
- Prevent hanging in closing state forever
- Don't force graceful exit if forceStop
- Fix connection closing in gRPC server
=> Handle edge cases in service starts

packages/orchestrator/internal/sandbox/template/storage.go
Fix nil pointer for old templates
=> Fix nil pointer for old templates

packages/orchestrator/internal/template/build/command.go
Nil dereference in template manager in run command
=> Nil dereference in template manager in run command

packages/orchestrator/internal/sandbox/template/storage.go
Fix memfile header for old templates
=> Fix memfile header for old templates

packages/cluster/scripts/run-api-nomad.sh, packages/cluster/scripts/run-build-cluster-nomad.sh, packages/cluster/scripts/run-nomad.sh
Fix readonly variable that shouldn't be readonly
=> Fix readonly variable

packages/orchestrator/internal/sandbox/fc/client_linux.go
Fix setting mmds config in template build. This is a regression
=> Fix sandbox logs reporting for new templates

packages/orchestrator/internal/template/build/ext4/tools.go
Sync enlarge ext4 file. This might help fixing filesystem corruption after enlarging.
=> Sync enlarge ext4 file

.github/workflows/periodic-test.yml
Turn off Juliett tests temporarily
=> Disable Juliett tests

.github/workflows/periodic-test.yml
Send alerts for periodic tests through Grafana alerts
=> Periodic tests Grafana alert

.github/workflows/periodic-test.yml
=> Reenable juliett test

terraform/grafana/stack/dashboards/main/panels/build-nodes-cpu-utilization.json
Fix incorrect Grafana panel project name
=> Fix incorrect Grafana panel project name

packages/shared/scripts/seed/postgres/seed-db.go, tests/integration/seed.go
Fix API keys seed db. Fixes https://github.com/e2b-dev/infra/issues/716
=> Fix API keys seed db

packages/nomad/template-manager.hcl, packages/orchestrator/internal/grpcserver/server.go, packages/orchestrator/internal/sandbox/fc/filtered_writer.go, packages/orchestrator/internal/sandbox/fc/process.go, packages/orchestrator/internal/template/build/ext4/tools.go, packages/orchestrator/internal/template/build/provision.sh, packages/orchestrator/internal/template/build/rootfs.go, packages/orchestrator/internal/template/build/template_builder.go, packages/orchestrator/internal/template/build/writer/filtered_writer.go
Expose provision logs during template build to the user.
Includes also:
- don't wait 30 seconds for template manager start
- filter `/InfoService/ServiceInfo` requests from logs
- fixes closed stdout and stderr error on sandbox exit (`error reading fc stdout/stderr, read |0: file already closed`)
- fail fast on provision.sh script failure
**Example**
```
[2025-06-03T13:42:17Z] Starting postprocessing
[2025-06-03T13:42:17Z] Requesting Docker Image
[2025-06-03T13:42:17Z] Docker image size: 467 MB
[2025-06-03T13:42:17Z] Setting up system files
[2025-06-03T13:42:17Z] Creating file system and pulling Docker image
[2025-06-03T13:42:22Z] ...
[2025-06-03T13:42:27Z] ...
[2025-06-03T13:42:32Z] ...
[2025-06-03T13:42:37Z] ...
[2025-06-03T13:42:40Z] Filesystem cleanup
[2025-06-03T13:42:41Z] …
```
=> Expose provision logs during template build

packages/cluster/clickhouse-cluster/variables.tf, packages/cluster/main.tf, packages/cluster/variables.tf
Adds a prefix to instance group and its resources
=> Add prefix to clickhouse cluster

main.tf, variables.tf
Add missing default variable for template bucket
=> Add missing default variable for template bucket

packages/orchestrator/internal/template/build/ext4/tools.go
Handle e2fsck repair exit codes when the repair is allowed. The acceptable exit codes when repair is allowed are 0, 1, 2 (the check is run on offline disk, reboot is done by booting).
> The exit code returned by e2fsck is the sum of the following conditions:
0 - No errors
1 - File system errors corrected
2 - File system errors corrected, system should be rebooted
4 - File system errors left uncorrected
8 - Operational error
16 - Usage or syntax error
32 - E2fsck canceled by user request
128 - Shared library error
=> Handle e2fsck repair exit codes

.github/actions/build-sandbox-template/action.yml, .github/actions/host-init/action.yml, .github/actions/host-init/init-client.sh, .github/actions/start-services/action.yml, packages/orchestrator/internal/template/build/template_builder.go
Remove GCP dependency from integration tests
=> Remove GCP from integration tests

packages/cluster/network/main.tf
Change sandbox start rate limit
=> Change the sandbox start rate limit

packages/cluster/client/main.tf
Fixes a bug when the max cluster size isn't set
=> Fix if max size isn't set

packages/nomad/main.tf, packages/nomad/orchestrator.hcl, packages/nomad/variables.tf, packages/orchestrator/internal/config/config.go, packages/orchestrator/internal/sandbox/checks.go, packages/orchestrator/internal/sandbox/metrics.go, packages/orchestrator/internal/sandbox/sandbox.go, packages/orchestrator/internal/server/main.go, packages/orchestrator/internal/server/sandboxes.go
Remove sending metrics to loki
=> Remove loki metrics

main.tf, variables.tf
Remove unused Loki metrics var
=> Remove unused Loki metrics var

packages/api/internal/dns/server.go, packages/api/internal/handlers/store.go, packages/api/internal/orchestrator/orchestrator.go, packages/nomad/api.hcl, packages/nomad/main.tf
This was there only for migration purposes, it's safe to remove now
=> Remove doubled Redis

.github/workflows/build-and-upload-job.yml, .github/workflows/deploy-infra.yml, .github/workflows/deploy-job.yml, Makefile, scripts/confirm.sh
Deployments should be now done from main
=> Update confirm script

packages/nomad/main.tf
Run clickhouse if dedicated node are present
=> Run Clickhouse if nodes available

Makefile, main.tf, packages/nomad/clickhouse.hcl, packages/nomad/main.tf, packages/nomad/variables.tf, variables.tf
Small improvements to clickhouse job config
- Allow customizing resources
- Add restart policy
- Clean up unused stuff / old todos
=> Clickhouse nomad job update config

packages/orchestrator/cmd/benchmark-metrics/main.go, packages/orchestrator/internal/server/main.go, packages/orchestrator/main.go, packages/shared/pkg/telemetry/sandbox.go
Adds a benchmark script for inserting sandbox metrics to clickhouse
=> Add benchmark clickhouse script

.github/workflows/deploy-infra.yml, Makefile, packages/db/Dockerfile, packages/db/Makefile, packages/db/go.mod, packages/db/scripts/migrator.go, packages/nomad/api.hcl, packages/nomad/main.tf
Apply API migrations before API starts
=> Add API migrator

packages/orchestrator/internal/sandbox/checks.go
When envd version is lower than the minimum for metrics it returned `nil` and no error causing panic
=> Check for envd version before trying to scrape metrics

packages/api/internal/orchestrator/cache.go, packages/api/internal/orchestrator/client.go, packages/api/internal/orchestrator/metrics.go, packages/api/internal/orchestrator/node.go, packages/api/internal/orchestrator/orchestrator.go, packages/shared/pkg/telemetry/meters.go
- Report correct status for the node if we can't connect to it
- Add a metric to monitor node status
=> API - Orchestrator status - Return unhealthy if cant connect

packages/orchestrator/internal/template/build/ext4/tools.go
Fix overlayfs mount with more than 4096 chars in lowerdir field by using modern FS mount - FSCONFIG_SET_STRING (https://docs.kernel.org/filesystems/overlayfs.html). Requires kernel version 6.8 or later.
When there are many layers (cca 38+), the lowerdir string exceeds mount arg threshold and is cut off. As a result, this will fail to properly mount the overlay filesystem.
=> Fix overlayfs mount with more than 4096 chars

packages/api/internal/edge/cluster.go
Small grammar change to make it sound more natural.
=> Fix grammar

.env.template
Update outdated `.env` with new expected variables
Addresses: #850
=> Update dotenv for client cluster size

self-host.md
With the clickhouse addition, requirements are now higher, let's reflect that.
=> Update self-host.md - small update to GCP requirements

packages/api/internal/template-manager/template_status.go
Use the context with a timeout for the build sync
=> Increase the timeout to 1 hour and use the correct context

packages/nomad/configs/otel-collector.yaml, packages/nomad/otel-collector.hcl
- Add otel collector metrics 
- Set resource names on all metrics
- Fix incorrect name (nomad_client_allocs_cpu_usage -> nomad_client_allocs_cpu_total_percent)
=> Add OTEL collector metrics

packages/envd/go.mod, packages/envd/internal/services/filesystem/dir.go, packages/envd/internal/services/filesystem/dir_test.go, packages/envd/main.go, tests/integration/internal/tests/envd/filesystem_test.go
Return whole path not only relative one
=> Fix envd resolving path

packages/orchestrator/internal/server/sandboxes.go
If the context is canceled (e.g. timeout), the cleanup is not run properly. This PR tries to fix it by running the cleanup using the background context
=> Fix sandbox cleanup on timeout error

packages/orchestrator/internal/template/build/command/run.go
Allow specifying custom user for the RUN `[command optional_user]`
=> Allow specifying custom user for the RUN

.github/actions/build-sandbox-template/action.yml, packages/orchestrator/cmd/build-template/main.go
Speed up integration tests base build by skipping Docker image pull/push
=> Speed up tests base build

packages/orchestrator/internal/sandbox/uffd/handler.go, packages/orchestrator/internal/sandbox/uffd/mapping/firecracker.go, packages/orchestrator/internal/sandbox/uffd/mapping/mapping.go, packages/orchestrator/internal/sandbox/uffd/serve.go
Extract UFFD mapping handling to prepare for adding UFFD write protection.
=> Refactor UFFD mapping handling

.golangci.yml
implementation: https://github.com/tdakkota/asciicheck
=> Add asciicheck linter

.github/actions/deploy-setup/action.yml, scripts/download-prod-env.sh
Fix Infisical export format to remove the '' (Makefile can't interpret them)
=> Fix Infisical export format

packages/api/internal/orchestrator/placement/placement.go, tests/integration/internal/tests/api/sandbox_internet_test.go, tests/integration/internal/tests/envd/localhost_bind_test.go
Remove parallel from sandbox integration tests
=> Remove parallel tests

packages/api/internal/handlers/sandboxes_list.go, packages/api/internal/handlers/store.go, packages/api/internal/orchestrator/create_instance.go, packages/api/internal/orchestrator/orchestrator.go, packages/api/internal/orchestrator/placement/placement.go, packages/api/internal/orchestrator/placement/placement_best_of_K.go, packages/api/internal/orchestrator/placement/placement_best_of_K_test.go, packages/api/internal/orchestrator/placement/placement_least_busy.go, packages/api/internal/orchestrator/placement/placement_test.go, packages/orchestrator/internal/metrics/sandboxes.go, packages/shared/pkg/feature-flags/client.go, packages/shared/pkg/feature-flags/flags.go, packages/shared/pkg/limit/limiter.go
Add feature flags to choose and customize best of K placing algorithm
=> Add feature flags for placing algorithm

packages/api/go.mod, packages/api/go.sum, packages/api/internal/middleware/logging.go, packages/api/main.go
This should help with cleaning up error logs
=> Decrease log level for user errors

.devcontainer/devcontainer.json
Update devcontainer.json setup
- Includes compatible Terraform version
- GCloud CLI
=> Update devcontainer.json setup

packages/api/internal/handlers/sandboxes_list.go, tests/integration/internal/tests/api/sandbox_list_test.go
Remove `X-Total-Items` as it's rather confusing
Add `X-Total-Running`
=> Return total count for running sandboxes

.golangci.yml
no changes, but good to have anyway
https://github.com/ldez/exptostd
=> enable exptostd linter

iac/provider-gcp/nomad/jobs/template-manager.hcl
This pull request updates the Nomad job specification for the `template-manager-system` to adjust the rolling update strategy.
=> Template manager - Remove incorrect arguments, add stagger

iac/provider-gcp/Makefile, iac/provider-gcp/main.tf, iac/provider-gcp/nomad/jobs/api.hcl, iac/provider-gcp/nomad/main.tf, iac/provider-gcp/nomad/variables.tf, iac/provider-gcp/variables.tf
This pull request adds configurable resource limits for the API service
=> Make it possible to customize API resources

packages/orchestrator/internal/template/build/phases/finalize/ready.go
Increase ready command timeout from 5 to 10 minutes.
=> Increase ready command timeout

iac/provider-gcp/nomad/jobs/template-manager.hcl
Remove delay from template manager deploy
=> Remove delay from template manager deploy

packages/orchestrator/internal/template/server/create_template.go
Add attributes to template build error
=> Add attributes to template build error

.github/workflows/lint.yml, .tool-versions, Makefile
This gets us access to more linters
=> Upgrade golangci-lint to 2.4.0

.golangci.yml, packages/envd/internal/services/legacy/conversion_test.go
https://github.com/butuzov/mirror
=> Add the mirror linter

.golangci.yml, packages/shared/pkg/telemetry/tracing.go
https://github.com/jjti/go-spancheck
=> add the spancheck linter

.golangci.yml, packages/api/internal/handlers/sandboxes_list.go, packages/api/internal/middleware/otel/metrics/middleware.go, packages/orchestrator/internal/sandbox/block/cache.go, packages/orchestrator/internal/sandbox/uffd/serve.go, packages/orchestrator/internal/sandbox/uffd/userfaultfd/constants.go, packages/orchestrator/main.go, tests/integration/internal/tests/api/sandboxes/sandbox_list_test.go
https://github.com/mdempsky/unconvert
=> Add unconvert linter, remove unnecessary conversions

.env.template, iac/provider-gcp/nomad-cluster/network/main.tf
Simplified version of #1213 from @ken8203 with support for nested subdomain
It doesn't work for domains such as `co.uk`
```
> E2B_DOMAIN=test.test.krindapana.dev e2b sbx sp base
Terminal connecting to template base with sandbox ID il6uqqqngkjdqtatvrzsj
user@e2b:~$ ^C
```
=> feat: Add subdomain support for Cloudflare DNS

packages/api/Dockerfile, packages/clickhouse/Dockerfile, packages/client-proxy/Dockerfile, packages/db/Dockerfile, packages/docker-reverse-proxy/Dockerfile, packages/envd/generate.Dockerfile, packages/orchestrator/Dockerfile, packages/orchestrator/test.Dockerfile
This should make future upgrades more obvious
=> Point dockerfile versions at arguments

.golangci.yml, packages/client-proxy/internal/edge-pass-through/events.go, packages/shared/pkg/storage/gcp_multipart_test.go
Now we have to make a public explicit decision to stop using a linter
=> Invert the list of linters

.golangci.yml, packages/shared/pkg/utils/resizable_semaphore_test.go
=> Enable the 'defer' revive rule

.golangci.yml, packages/api/internal/orchestrator/nodemanager/mock.go, packages/api/internal/orchestrator/placement/placement_benchmark_test.go, packages/api/internal/utils/sandboxes_list.go, packages/clickhouse/pkg/batcher/product_usage_insert_batcher.go, packages/clickhouse/pkg/batcher/sandbox_events_insert_batcher.go, packages/db/client/client.go, packages/orchestrator/internal/sandbox/build/local_diff.go, packages/orchestrator/internal/template/build/writer/filtered_writer.go, packages/orchestrator/internal/template/server/main.go, packages/shared/pkg/proxy/pool/client.go, packages/shared/pkg/proxy/proxy.go, packages/shared/pkg/proxy/tracking/connection.go, packages/shared/pkg/proxy/tracking/listener.go, packages/shared/pkg/storage/sandbox.go, packages/shared/pkg/storage/storage_fs.go, packages/shared/pkg/storage/template_cache.go
https://github.com/manuelarte/embeddedstructfieldcheck
=> add embeddedstructfieldcheck linter

packages/orchestrator/internal/template/build/commands/copy.go
Fix symlink file move after unpacking the archive. Fixes single symlink file copy.
=> Fix symlink file move after unpacking the archive
